// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumicephradosgw

import (
	"context"
	"reflect"

	"github.com/OSMIT-GmbH/pulumi-ceph-radosgw/sdk/go/pulumi-ceph-radosgw/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Provider struct {
	pulumi.ProviderResourceState

	// The username. It's important but not secret.
	AccessKeyID pulumi.StringPtrOutput `pulumi:"accessKeyID"`
	// Assimilate an existing object during create
	Assimilate pulumi.StringPtrOutput `pulumi:"assimilate"`
	// Delete assimilated objects during delete (otherwise they would be kept on OpenZiti)
	DeleteAssimilated pulumi.StringPtrOutput `pulumi:"deleteAssimilated"`
	// The URI to the API
	Endpoint pulumi.StringPtrOutput `pulumi:"endpoint"`
	// Don't validate server SSL certificate
	Insecure pulumi.StringPtrOutput `pulumi:"insecure"`
	// The password. It is very secret.
	SecretAccessKey pulumi.StringPtrOutput `pulumi:"secretAccessKey"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.SecretAccessKey != nil {
		args.SecretAccessKey = pulumi.ToSecret(args.SecretAccessKey).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"secretAccessKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:ceph-radosgw", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// The username. It's important but not secret.
	AccessKeyID *string `pulumi:"accessKeyID"`
	// Assimilate an existing object during create
	Assimilate *string `pulumi:"assimilate"`
	// Delete assimilated objects during delete (otherwise they would be kept on OpenZiti)
	DeleteAssimilated *string `pulumi:"deleteAssimilated"`
	// The URI to the API
	Endpoint *string `pulumi:"endpoint"`
	// Don't validate server SSL certificate
	Insecure *string `pulumi:"insecure"`
	// The password. It is very secret.
	SecretAccessKey *string `pulumi:"secretAccessKey"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// The username. It's important but not secret.
	AccessKeyID pulumi.StringPtrInput
	// Assimilate an existing object during create
	Assimilate pulumi.StringPtrInput
	// Delete assimilated objects during delete (otherwise they would be kept on OpenZiti)
	DeleteAssimilated pulumi.StringPtrInput
	// The URI to the API
	Endpoint pulumi.StringPtrInput
	// Don't validate server SSL certificate
	Insecure pulumi.StringPtrInput
	// The password. It is very secret.
	SecretAccessKey pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// The username. It's important but not secret.
func (o ProviderOutput) AccessKeyID() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.AccessKeyID }).(pulumi.StringPtrOutput)
}

// Assimilate an existing object during create
func (o ProviderOutput) Assimilate() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Assimilate }).(pulumi.StringPtrOutput)
}

// Delete assimilated objects during delete (otherwise they would be kept on OpenZiti)
func (o ProviderOutput) DeleteAssimilated() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.DeleteAssimilated }).(pulumi.StringPtrOutput)
}

// The URI to the API
func (o ProviderOutput) Endpoint() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Endpoint }).(pulumi.StringPtrOutput)
}

// Don't validate server SSL certificate
func (o ProviderOutput) Insecure() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Insecure }).(pulumi.StringPtrOutput)
}

// The password. It is very secret.
func (o ProviderOutput) SecretAccessKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.SecretAccessKey }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
