// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumicephradosgw

import (
	"context"
	"reflect"

	"errors"
	"github.com/OSMIT-GmbH/pulumi-ceph-radosgw/sdk/go/pulumi-ceph-radosgw/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SubUser struct {
	pulumi.CustomResourceState

	_assimilated pulumi.BoolOutput       `pulumi:"_assimilated"`
	Fullname     pulumi.StringOutput     `pulumi:"fullname"`
	GenerateKey  pulumi.BoolPtrOutput    `pulumi:"generateKey"`
	KeyType      KeyTypePtrOutput        `pulumi:"keyType"`
	Keys         KeyEntryArrayOutput     `pulumi:"keys"`
	Permissions  SubUserPermissionOutput `pulumi:"permissions"`
	PurgeKeys    pulumi.BoolPtrOutput    `pulumi:"purgeKeys"`
	SecretKey    pulumi.StringPtrOutput  `pulumi:"secretKey"`
	// Name of this subuser
	SubUserName pulumi.StringOutput `pulumi:"subUserName"`
	// User-ID of 'parent' user
	UserId pulumi.StringOutput `pulumi:"userId"`
}

// NewSubUser registers a new resource with the given unique name, arguments, and options.
func NewSubUser(ctx *pulumi.Context,
	name string, args *SubUserArgs, opts ...pulumi.ResourceOption) (*SubUser, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Permissions == nil {
		return nil, errors.New("invalid value for required argument 'Permissions'")
	}
	if args.SubUserName == nil {
		return nil, errors.New("invalid value for required argument 'SubUserName'")
	}
	if args.UserId == nil {
		return nil, errors.New("invalid value for required argument 'UserId'")
	}
	if args.SecretKey != nil {
		args.SecretKey = pulumi.ToSecret(args.SecretKey).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"secretKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SubUser
	err := ctx.RegisterResource("ceph-radosgw:index:SubUser", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSubUser gets an existing SubUser resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSubUser(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SubUserState, opts ...pulumi.ResourceOption) (*SubUser, error) {
	var resource SubUser
	err := ctx.ReadResource("ceph-radosgw:index:SubUser", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SubUser resources.
type subUserState struct {
}

type SubUserState struct {
}

func (SubUserState) ElementType() reflect.Type {
	return reflect.TypeOf((*subUserState)(nil)).Elem()
}

type subUserArgs struct {
	GenerateKey *bool             `pulumi:"generateKey"`
	KeyType     *KeyType          `pulumi:"keyType"`
	Permissions SubUserPermission `pulumi:"permissions"`
	PurgeKeys   *bool             `pulumi:"purgeKeys"`
	SecretKey   *string           `pulumi:"secretKey"`
	// Name of this subuser
	SubUserName string `pulumi:"subUserName"`
	// User-ID of 'parent' user
	UserId string `pulumi:"userId"`
}

// The set of arguments for constructing a SubUser resource.
type SubUserArgs struct {
	GenerateKey pulumi.BoolPtrInput
	KeyType     KeyTypePtrInput
	Permissions SubUserPermissionInput
	PurgeKeys   pulumi.BoolPtrInput
	SecretKey   pulumi.StringPtrInput
	// Name of this subuser
	SubUserName pulumi.StringInput
	// User-ID of 'parent' user
	UserId pulumi.StringInput
}

func (SubUserArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*subUserArgs)(nil)).Elem()
}

type SubUserInput interface {
	pulumi.Input

	ToSubUserOutput() SubUserOutput
	ToSubUserOutputWithContext(ctx context.Context) SubUserOutput
}

func (*SubUser) ElementType() reflect.Type {
	return reflect.TypeOf((**SubUser)(nil)).Elem()
}

func (i *SubUser) ToSubUserOutput() SubUserOutput {
	return i.ToSubUserOutputWithContext(context.Background())
}

func (i *SubUser) ToSubUserOutputWithContext(ctx context.Context) SubUserOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SubUserOutput)
}

// SubUserArrayInput is an input type that accepts SubUserArray and SubUserArrayOutput values.
// You can construct a concrete instance of `SubUserArrayInput` via:
//
//	SubUserArray{ SubUserArgs{...} }
type SubUserArrayInput interface {
	pulumi.Input

	ToSubUserArrayOutput() SubUserArrayOutput
	ToSubUserArrayOutputWithContext(context.Context) SubUserArrayOutput
}

type SubUserArray []SubUserInput

func (SubUserArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SubUser)(nil)).Elem()
}

func (i SubUserArray) ToSubUserArrayOutput() SubUserArrayOutput {
	return i.ToSubUserArrayOutputWithContext(context.Background())
}

func (i SubUserArray) ToSubUserArrayOutputWithContext(ctx context.Context) SubUserArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SubUserArrayOutput)
}

// SubUserMapInput is an input type that accepts SubUserMap and SubUserMapOutput values.
// You can construct a concrete instance of `SubUserMapInput` via:
//
//	SubUserMap{ "key": SubUserArgs{...} }
type SubUserMapInput interface {
	pulumi.Input

	ToSubUserMapOutput() SubUserMapOutput
	ToSubUserMapOutputWithContext(context.Context) SubUserMapOutput
}

type SubUserMap map[string]SubUserInput

func (SubUserMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SubUser)(nil)).Elem()
}

func (i SubUserMap) ToSubUserMapOutput() SubUserMapOutput {
	return i.ToSubUserMapOutputWithContext(context.Background())
}

func (i SubUserMap) ToSubUserMapOutputWithContext(ctx context.Context) SubUserMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SubUserMapOutput)
}

type SubUserOutput struct{ *pulumi.OutputState }

func (SubUserOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SubUser)(nil)).Elem()
}

func (o SubUserOutput) ToSubUserOutput() SubUserOutput {
	return o
}

func (o SubUserOutput) ToSubUserOutputWithContext(ctx context.Context) SubUserOutput {
	return o
}

func (o SubUserOutput) _assimilated() pulumi.BoolOutput {
	return o.ApplyT(func(v *SubUser) pulumi.BoolOutput { return v._assimilated }).(pulumi.BoolOutput)
}

func (o SubUserOutput) Fullname() pulumi.StringOutput {
	return o.ApplyT(func(v *SubUser) pulumi.StringOutput { return v.Fullname }).(pulumi.StringOutput)
}

func (o SubUserOutput) GenerateKey() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *SubUser) pulumi.BoolPtrOutput { return v.GenerateKey }).(pulumi.BoolPtrOutput)
}

func (o SubUserOutput) KeyType() KeyTypePtrOutput {
	return o.ApplyT(func(v *SubUser) KeyTypePtrOutput { return v.KeyType }).(KeyTypePtrOutput)
}

func (o SubUserOutput) Keys() KeyEntryArrayOutput {
	return o.ApplyT(func(v *SubUser) KeyEntryArrayOutput { return v.Keys }).(KeyEntryArrayOutput)
}

func (o SubUserOutput) Permissions() SubUserPermissionOutput {
	return o.ApplyT(func(v *SubUser) SubUserPermissionOutput { return v.Permissions }).(SubUserPermissionOutput)
}

func (o SubUserOutput) PurgeKeys() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *SubUser) pulumi.BoolPtrOutput { return v.PurgeKeys }).(pulumi.BoolPtrOutput)
}

func (o SubUserOutput) SecretKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SubUser) pulumi.StringPtrOutput { return v.SecretKey }).(pulumi.StringPtrOutput)
}

// Name of this subuser
func (o SubUserOutput) SubUserName() pulumi.StringOutput {
	return o.ApplyT(func(v *SubUser) pulumi.StringOutput { return v.SubUserName }).(pulumi.StringOutput)
}

// User-ID of 'parent' user
func (o SubUserOutput) UserId() pulumi.StringOutput {
	return o.ApplyT(func(v *SubUser) pulumi.StringOutput { return v.UserId }).(pulumi.StringOutput)
}

type SubUserArrayOutput struct{ *pulumi.OutputState }

func (SubUserArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SubUser)(nil)).Elem()
}

func (o SubUserArrayOutput) ToSubUserArrayOutput() SubUserArrayOutput {
	return o
}

func (o SubUserArrayOutput) ToSubUserArrayOutputWithContext(ctx context.Context) SubUserArrayOutput {
	return o
}

func (o SubUserArrayOutput) Index(i pulumi.IntInput) SubUserOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SubUser {
		return vs[0].([]*SubUser)[vs[1].(int)]
	}).(SubUserOutput)
}

type SubUserMapOutput struct{ *pulumi.OutputState }

func (SubUserMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SubUser)(nil)).Elem()
}

func (o SubUserMapOutput) ToSubUserMapOutput() SubUserMapOutput {
	return o
}

func (o SubUserMapOutput) ToSubUserMapOutputWithContext(ctx context.Context) SubUserMapOutput {
	return o
}

func (o SubUserMapOutput) MapIndex(k pulumi.StringInput) SubUserOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SubUser {
		return vs[0].(map[string]*SubUser)[vs[1].(string)]
	}).(SubUserOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SubUserInput)(nil)).Elem(), &SubUser{})
	pulumi.RegisterInputType(reflect.TypeOf((*SubUserArrayInput)(nil)).Elem(), SubUserArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SubUserMapInput)(nil)).Elem(), SubUserMap{})
	pulumi.RegisterOutputType(SubUserOutput{})
	pulumi.RegisterOutputType(SubUserArrayOutput{})
	pulumi.RegisterOutputType(SubUserMapOutput{})
}
