// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.cephradosgw.outputs;

import com.osmitgmbh.cephradosgw.enums.CapabilityPermission;
import com.pulumi.core.annotations.CustomType;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class Capabilities {
    private @Nullable CapabilityPermission amzCache;
    private @Nullable CapabilityPermission bilog;
    private @Nullable CapabilityPermission buckets;
    private @Nullable CapabilityPermission datalog;
    private @Nullable CapabilityPermission info;
    private @Nullable CapabilityPermission mdlog;
    private @Nullable CapabilityPermission metadata;
    private @Nullable CapabilityPermission oidcProvider;
    private @Nullable CapabilityPermission ratelimit;
    private @Nullable CapabilityPermission roles;
    private @Nullable CapabilityPermission usage;
    private @Nullable CapabilityPermission userPolicy;
    private @Nullable CapabilityPermission users;
    private @Nullable CapabilityPermission zone;

    private Capabilities() {}
    public Optional<CapabilityPermission> amzCache() {
        return Optional.ofNullable(this.amzCache);
    }
    public Optional<CapabilityPermission> bilog() {
        return Optional.ofNullable(this.bilog);
    }
    public Optional<CapabilityPermission> buckets() {
        return Optional.ofNullable(this.buckets);
    }
    public Optional<CapabilityPermission> datalog() {
        return Optional.ofNullable(this.datalog);
    }
    public Optional<CapabilityPermission> info() {
        return Optional.ofNullable(this.info);
    }
    public Optional<CapabilityPermission> mdlog() {
        return Optional.ofNullable(this.mdlog);
    }
    public Optional<CapabilityPermission> metadata() {
        return Optional.ofNullable(this.metadata);
    }
    public Optional<CapabilityPermission> oidcProvider() {
        return Optional.ofNullable(this.oidcProvider);
    }
    public Optional<CapabilityPermission> ratelimit() {
        return Optional.ofNullable(this.ratelimit);
    }
    public Optional<CapabilityPermission> roles() {
        return Optional.ofNullable(this.roles);
    }
    public Optional<CapabilityPermission> usage() {
        return Optional.ofNullable(this.usage);
    }
    public Optional<CapabilityPermission> userPolicy() {
        return Optional.ofNullable(this.userPolicy);
    }
    public Optional<CapabilityPermission> users() {
        return Optional.ofNullable(this.users);
    }
    public Optional<CapabilityPermission> zone() {
        return Optional.ofNullable(this.zone);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(Capabilities defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable CapabilityPermission amzCache;
        private @Nullable CapabilityPermission bilog;
        private @Nullable CapabilityPermission buckets;
        private @Nullable CapabilityPermission datalog;
        private @Nullable CapabilityPermission info;
        private @Nullable CapabilityPermission mdlog;
        private @Nullable CapabilityPermission metadata;
        private @Nullable CapabilityPermission oidcProvider;
        private @Nullable CapabilityPermission ratelimit;
        private @Nullable CapabilityPermission roles;
        private @Nullable CapabilityPermission usage;
        private @Nullable CapabilityPermission userPolicy;
        private @Nullable CapabilityPermission users;
        private @Nullable CapabilityPermission zone;
        public Builder() {}
        public Builder(Capabilities defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.amzCache = defaults.amzCache;
    	      this.bilog = defaults.bilog;
    	      this.buckets = defaults.buckets;
    	      this.datalog = defaults.datalog;
    	      this.info = defaults.info;
    	      this.mdlog = defaults.mdlog;
    	      this.metadata = defaults.metadata;
    	      this.oidcProvider = defaults.oidcProvider;
    	      this.ratelimit = defaults.ratelimit;
    	      this.roles = defaults.roles;
    	      this.usage = defaults.usage;
    	      this.userPolicy = defaults.userPolicy;
    	      this.users = defaults.users;
    	      this.zone = defaults.zone;
        }

        @CustomType.Setter
        public Builder amzCache(@Nullable CapabilityPermission amzCache) {

            this.amzCache = amzCache;
            return this;
        }
        @CustomType.Setter
        public Builder bilog(@Nullable CapabilityPermission bilog) {

            this.bilog = bilog;
            return this;
        }
        @CustomType.Setter
        public Builder buckets(@Nullable CapabilityPermission buckets) {

            this.buckets = buckets;
            return this;
        }
        @CustomType.Setter
        public Builder datalog(@Nullable CapabilityPermission datalog) {

            this.datalog = datalog;
            return this;
        }
        @CustomType.Setter
        public Builder info(@Nullable CapabilityPermission info) {

            this.info = info;
            return this;
        }
        @CustomType.Setter
        public Builder mdlog(@Nullable CapabilityPermission mdlog) {

            this.mdlog = mdlog;
            return this;
        }
        @CustomType.Setter
        public Builder metadata(@Nullable CapabilityPermission metadata) {

            this.metadata = metadata;
            return this;
        }
        @CustomType.Setter
        public Builder oidcProvider(@Nullable CapabilityPermission oidcProvider) {

            this.oidcProvider = oidcProvider;
            return this;
        }
        @CustomType.Setter
        public Builder ratelimit(@Nullable CapabilityPermission ratelimit) {

            this.ratelimit = ratelimit;
            return this;
        }
        @CustomType.Setter
        public Builder roles(@Nullable CapabilityPermission roles) {

            this.roles = roles;
            return this;
        }
        @CustomType.Setter
        public Builder usage(@Nullable CapabilityPermission usage) {

            this.usage = usage;
            return this;
        }
        @CustomType.Setter
        public Builder userPolicy(@Nullable CapabilityPermission userPolicy) {

            this.userPolicy = userPolicy;
            return this;
        }
        @CustomType.Setter
        public Builder users(@Nullable CapabilityPermission users) {

            this.users = users;
            return this;
        }
        @CustomType.Setter
        public Builder zone(@Nullable CapabilityPermission zone) {

            this.zone = zone;
            return this;
        }
        public Capabilities build() {
            final var _resultValue = new Capabilities();
            _resultValue.amzCache = amzCache;
            _resultValue.bilog = bilog;
            _resultValue.buckets = buckets;
            _resultValue.datalog = datalog;
            _resultValue.info = info;
            _resultValue.mdlog = mdlog;
            _resultValue.metadata = metadata;
            _resultValue.oidcProvider = oidcProvider;
            _resultValue.ratelimit = ratelimit;
            _resultValue.roles = roles;
            _resultValue.usage = usage;
            _resultValue.userPolicy = userPolicy;
            _resultValue.users = users;
            _resultValue.zone = zone;
            return _resultValue;
        }
    }
}
