// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.cephradosgw.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class KeyEntry {
    private @Nullable String accessKey;
    private String keyType;
    private String secretKey;

    private KeyEntry() {}
    public Optional<String> accessKey() {
        return Optional.ofNullable(this.accessKey);
    }
    public String keyType() {
        return this.keyType;
    }
    public String secretKey() {
        return this.secretKey;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(KeyEntry defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String accessKey;
        private String keyType;
        private String secretKey;
        public Builder() {}
        public Builder(KeyEntry defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accessKey = defaults.accessKey;
    	      this.keyType = defaults.keyType;
    	      this.secretKey = defaults.secretKey;
        }

        @CustomType.Setter
        public Builder accessKey(@Nullable String accessKey) {

            this.accessKey = accessKey;
            return this;
        }
        @CustomType.Setter
        public Builder keyType(String keyType) {
            if (keyType == null) {
              throw new MissingRequiredPropertyException("KeyEntry", "keyType");
            }
            this.keyType = keyType;
            return this;
        }
        @CustomType.Setter
        public Builder secretKey(String secretKey) {
            if (secretKey == null) {
              throw new MissingRequiredPropertyException("KeyEntry", "secretKey");
            }
            this.secretKey = secretKey;
            return this;
        }
        public KeyEntry build() {
            final var _resultValue = new KeyEntry();
            _resultValue.accessKey = accessKey;
            _resultValue.keyType = keyType;
            _resultValue.secretKey = secretKey;
            return _resultValue;
        }
    }
}
