// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.cephradosgw.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class QuotaArgs {
    /**
     * @return Enable or disable quota enforcement quota
     * 
     */
    private @Nullable Boolean enabled;
    /**
     * @return Maximum object count - numeric value (alternate to MaxObjectsHum)
     * 
     */
    private @Nullable Integer maxObjects;
    /**
     * @return Maximum object count - human readable format (i.e. 10k) (alternate to MaxObjects)
     * 
     */
    private @Nullable String maxObjectsHum;
    /**
     * @return Maximum size - numeric value (alternate to MaxSizeHum)
     * 
     */
    private @Nullable Integer maxSize;
    /**
     * @return Maximum size - human readable format (alternate to MaxSize)
     * 
     */
    private @Nullable String maxSizeHum;

    private QuotaArgs() {}
    /**
     * @return Enable or disable quota enforcement quota
     * 
     */
    public Optional<Boolean> enabled() {
        return Optional.ofNullable(this.enabled);
    }
    /**
     * @return Maximum object count - numeric value (alternate to MaxObjectsHum)
     * 
     */
    public Optional<Integer> maxObjects() {
        return Optional.ofNullable(this.maxObjects);
    }
    /**
     * @return Maximum object count - human readable format (i.e. 10k) (alternate to MaxObjects)
     * 
     */
    public Optional<String> maxObjectsHum() {
        return Optional.ofNullable(this.maxObjectsHum);
    }
    /**
     * @return Maximum size - numeric value (alternate to MaxSizeHum)
     * 
     */
    public Optional<Integer> maxSize() {
        return Optional.ofNullable(this.maxSize);
    }
    /**
     * @return Maximum size - human readable format (alternate to MaxSize)
     * 
     */
    public Optional<String> maxSizeHum() {
        return Optional.ofNullable(this.maxSizeHum);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(QuotaArgs defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean enabled;
        private @Nullable Integer maxObjects;
        private @Nullable String maxObjectsHum;
        private @Nullable Integer maxSize;
        private @Nullable String maxSizeHum;
        public Builder() {}
        public Builder(QuotaArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.enabled = defaults.enabled;
    	      this.maxObjects = defaults.maxObjects;
    	      this.maxObjectsHum = defaults.maxObjectsHum;
    	      this.maxSize = defaults.maxSize;
    	      this.maxSizeHum = defaults.maxSizeHum;
        }

        @CustomType.Setter
        public Builder enabled(@Nullable Boolean enabled) {

            this.enabled = enabled;
            return this;
        }
        @CustomType.Setter
        public Builder maxObjects(@Nullable Integer maxObjects) {

            this.maxObjects = maxObjects;
            return this;
        }
        @CustomType.Setter
        public Builder maxObjectsHum(@Nullable String maxObjectsHum) {

            this.maxObjectsHum = maxObjectsHum;
            return this;
        }
        @CustomType.Setter
        public Builder maxSize(@Nullable Integer maxSize) {

            this.maxSize = maxSize;
            return this;
        }
        @CustomType.Setter
        public Builder maxSizeHum(@Nullable String maxSizeHum) {

            this.maxSizeHum = maxSizeHum;
            return this;
        }
        public QuotaArgs build() {
            final var _resultValue = new QuotaArgs();
            _resultValue.enabled = enabled;
            _resultValue.maxObjects = maxObjects;
            _resultValue.maxObjectsHum = maxObjectsHum;
            _resultValue.maxSize = maxSize;
            _resultValue.maxSizeHum = maxSizeHum;
            return _resultValue;
        }
    }
}
