// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CephRadosgw
{
    [CephRadosgwResourceType("pulumi:providers:ceph-radosgw")]
    public partial class Provider : global::Pulumi.ProviderResource
    {
        /// <summary>
        /// The username. It's important but not secret.
        /// </summary>
        [Output("accessKeyID")]
        public Output<string> AccessKeyID { get; private set; } = null!;

        /// <summary>
        /// Assimilate an existing object during create
        /// </summary>
        [Output("assimilate")]
        public Output<string?> Assimilate { get; private set; } = null!;

        /// <summary>
        /// Delete assimilated objects during delete (otherwise they would be kept on OpenZiti)
        /// </summary>
        [Output("deleteAssimilated")]
        public Output<string?> DeleteAssimilated { get; private set; } = null!;

        /// <summary>
        /// The URI to the API
        /// </summary>
        [Output("endpoint")]
        public Output<string> Endpoint { get; private set; } = null!;

        /// <summary>
        /// The password. It is very secret.
        /// </summary>
        [Output("secretAccessKey")]
        public Output<string> SecretAccessKey { get; private set; } = null!;

        [Output("version")]
        public Output<string?> Version { get; private set; } = null!;


        /// <summary>
        /// Create a Provider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Provider(string name, ProviderArgs args, CustomResourceOptions? options = null)
            : base("ceph-radosgw", name, args ?? new ProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "secretAccessKey",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ProviderArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The username. It's important but not secret.
        /// </summary>
        [Input("accessKeyID", required: true)]
        public Input<string> AccessKeyID { get; set; } = null!;

        /// <summary>
        /// Assimilate an existing object during create
        /// </summary>
        [Input("assimilate")]
        public Input<string>? Assimilate { get; set; }

        /// <summary>
        /// Delete assimilated objects during delete (otherwise they would be kept on OpenZiti)
        /// </summary>
        [Input("deleteAssimilated")]
        public Input<string>? DeleteAssimilated { get; set; }

        /// <summary>
        /// The URI to the API
        /// </summary>
        [Input("endpoint", required: true)]
        public Input<string> Endpoint { get; set; } = null!;

        [Input("secretAccessKey", required: true)]
        private Input<string>? _secretAccessKey;

        /// <summary>
        /// The password. It is very secret.
        /// </summary>
        public Input<string>? SecretAccessKey
        {
            get => _secretAccessKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _secretAccessKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("version")]
        public Input<string>? Version { get; set; }

        public ProviderArgs()
        {
        }
        public static new ProviderArgs Empty => new ProviderArgs();
    }
}
