# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    'CapabilityPermission',
    'KeyType',
    'SubUserPermission',
]


@pulumi.type_token("ceph-radosgw:index:CapabilityPermission")
class CapabilityPermission(_builtins.str, Enum):
    READ = "read"
    WRITE = "write"
    ASTERISK = "*"


@pulumi.type_token("ceph-radosgw:index:KeyType")
class KeyType(_builtins.str, Enum):
    S3 = "s3"
    SWIFT = "swift"


@pulumi.type_token("ceph-radosgw:index:SubUserPermission")
class SubUserPermission(_builtins.str, Enum):
    NONE = "none"
    READ = "read"
    WRITE = "write"
    READ_WRITE = "readWrite"
    FULL_CONTROL = "fullControl"
