# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._enums import *

__all__ = [
    'CapabilitiesArgs',
    'CapabilitiesArgsDict',
    'QuotaArgsArgs',
    'QuotaArgsArgsDict',
]

class CapabilitiesArgsDict(TypedDict):
    amz_cache: NotRequired[pulumi.Input[Optional['CapabilityPermission']]]
    bilog: NotRequired[pulumi.Input[Optional['CapabilityPermission']]]
    buckets: NotRequired[pulumi.Input[Optional['CapabilityPermission']]]
    datalog: NotRequired[pulumi.Input[Optional['CapabilityPermission']]]
    info: NotRequired[pulumi.Input[Optional['CapabilityPermission']]]
    mdlog: NotRequired[pulumi.Input[Optional['CapabilityPermission']]]
    metadata: NotRequired[pulumi.Input[Optional['CapabilityPermission']]]
    oidc_provider: NotRequired[pulumi.Input[Optional['CapabilityPermission']]]
    ratelimit: NotRequired[pulumi.Input[Optional['CapabilityPermission']]]
    roles: NotRequired[pulumi.Input[Optional['CapabilityPermission']]]
    usage: NotRequired[pulumi.Input[Optional['CapabilityPermission']]]
    user_policy: NotRequired[pulumi.Input[Optional['CapabilityPermission']]]
    users: NotRequired[pulumi.Input[Optional['CapabilityPermission']]]
    zone: NotRequired[pulumi.Input[Optional['CapabilityPermission']]]

@pulumi.input_type
class CapabilitiesArgs:
    def __init__(__self__, *,
                 amz_cache: pulumi.Input[Optional['CapabilityPermission']] = None,
                 bilog: pulumi.Input[Optional['CapabilityPermission']] = None,
                 buckets: pulumi.Input[Optional['CapabilityPermission']] = None,
                 datalog: pulumi.Input[Optional['CapabilityPermission']] = None,
                 info: pulumi.Input[Optional['CapabilityPermission']] = None,
                 mdlog: pulumi.Input[Optional['CapabilityPermission']] = None,
                 metadata: pulumi.Input[Optional['CapabilityPermission']] = None,
                 oidc_provider: pulumi.Input[Optional['CapabilityPermission']] = None,
                 ratelimit: pulumi.Input[Optional['CapabilityPermission']] = None,
                 roles: pulumi.Input[Optional['CapabilityPermission']] = None,
                 usage: pulumi.Input[Optional['CapabilityPermission']] = None,
                 user_policy: pulumi.Input[Optional['CapabilityPermission']] = None,
                 users: pulumi.Input[Optional['CapabilityPermission']] = None,
                 zone: pulumi.Input[Optional['CapabilityPermission']] = None):
        if amz_cache is not None:
            pulumi.set(__self__, "amz_cache", amz_cache)
        if bilog is not None:
            pulumi.set(__self__, "bilog", bilog)
        if buckets is not None:
            pulumi.set(__self__, "buckets", buckets)
        if datalog is not None:
            pulumi.set(__self__, "datalog", datalog)
        if info is not None:
            pulumi.set(__self__, "info", info)
        if mdlog is not None:
            pulumi.set(__self__, "mdlog", mdlog)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if oidc_provider is not None:
            pulumi.set(__self__, "oidc_provider", oidc_provider)
        if ratelimit is not None:
            pulumi.set(__self__, "ratelimit", ratelimit)
        if roles is not None:
            pulumi.set(__self__, "roles", roles)
        if usage is not None:
            pulumi.set(__self__, "usage", usage)
        if user_policy is not None:
            pulumi.set(__self__, "user_policy", user_policy)
        if users is not None:
            pulumi.set(__self__, "users", users)
        if zone is not None:
            pulumi.set(__self__, "zone", zone)

    @_builtins.property
    @pulumi.getter(name="amzCache")
    def amz_cache(self) -> pulumi.Input[Optional['CapabilityPermission']]:
        return pulumi.get(self, "amz_cache")

    @amz_cache.setter
    def amz_cache(self, value: pulumi.Input[Optional['CapabilityPermission']]):
        pulumi.set(self, "amz_cache", value)

    @_builtins.property
    @pulumi.getter
    def bilog(self) -> pulumi.Input[Optional['CapabilityPermission']]:
        return pulumi.get(self, "bilog")

    @bilog.setter
    def bilog(self, value: pulumi.Input[Optional['CapabilityPermission']]):
        pulumi.set(self, "bilog", value)

    @_builtins.property
    @pulumi.getter
    def buckets(self) -> pulumi.Input[Optional['CapabilityPermission']]:
        return pulumi.get(self, "buckets")

    @buckets.setter
    def buckets(self, value: pulumi.Input[Optional['CapabilityPermission']]):
        pulumi.set(self, "buckets", value)

    @_builtins.property
    @pulumi.getter
    def datalog(self) -> pulumi.Input[Optional['CapabilityPermission']]:
        return pulumi.get(self, "datalog")

    @datalog.setter
    def datalog(self, value: pulumi.Input[Optional['CapabilityPermission']]):
        pulumi.set(self, "datalog", value)

    @_builtins.property
    @pulumi.getter
    def info(self) -> pulumi.Input[Optional['CapabilityPermission']]:
        return pulumi.get(self, "info")

    @info.setter
    def info(self, value: pulumi.Input[Optional['CapabilityPermission']]):
        pulumi.set(self, "info", value)

    @_builtins.property
    @pulumi.getter
    def mdlog(self) -> pulumi.Input[Optional['CapabilityPermission']]:
        return pulumi.get(self, "mdlog")

    @mdlog.setter
    def mdlog(self, value: pulumi.Input[Optional['CapabilityPermission']]):
        pulumi.set(self, "mdlog", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Input[Optional['CapabilityPermission']]:
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: pulumi.Input[Optional['CapabilityPermission']]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter(name="oidcProvider")
    def oidc_provider(self) -> pulumi.Input[Optional['CapabilityPermission']]:
        return pulumi.get(self, "oidc_provider")

    @oidc_provider.setter
    def oidc_provider(self, value: pulumi.Input[Optional['CapabilityPermission']]):
        pulumi.set(self, "oidc_provider", value)

    @_builtins.property
    @pulumi.getter
    def ratelimit(self) -> pulumi.Input[Optional['CapabilityPermission']]:
        return pulumi.get(self, "ratelimit")

    @ratelimit.setter
    def ratelimit(self, value: pulumi.Input[Optional['CapabilityPermission']]):
        pulumi.set(self, "ratelimit", value)

    @_builtins.property
    @pulumi.getter
    def roles(self) -> pulumi.Input[Optional['CapabilityPermission']]:
        return pulumi.get(self, "roles")

    @roles.setter
    def roles(self, value: pulumi.Input[Optional['CapabilityPermission']]):
        pulumi.set(self, "roles", value)

    @_builtins.property
    @pulumi.getter
    def usage(self) -> pulumi.Input[Optional['CapabilityPermission']]:
        return pulumi.get(self, "usage")

    @usage.setter
    def usage(self, value: pulumi.Input[Optional['CapabilityPermission']]):
        pulumi.set(self, "usage", value)

    @_builtins.property
    @pulumi.getter(name="userPolicy")
    def user_policy(self) -> pulumi.Input[Optional['CapabilityPermission']]:
        return pulumi.get(self, "user_policy")

    @user_policy.setter
    def user_policy(self, value: pulumi.Input[Optional['CapabilityPermission']]):
        pulumi.set(self, "user_policy", value)

    @_builtins.property
    @pulumi.getter
    def users(self) -> pulumi.Input[Optional['CapabilityPermission']]:
        return pulumi.get(self, "users")

    @users.setter
    def users(self, value: pulumi.Input[Optional['CapabilityPermission']]):
        pulumi.set(self, "users", value)

    @_builtins.property
    @pulumi.getter
    def zone(self) -> pulumi.Input[Optional['CapabilityPermission']]:
        return pulumi.get(self, "zone")

    @zone.setter
    def zone(self, value: pulumi.Input[Optional['CapabilityPermission']]):
        pulumi.set(self, "zone", value)


class QuotaArgsArgsDict(TypedDict):
    enabled: NotRequired[pulumi.Input[Optional[_builtins.bool]]]
    """
    Enable or disable quota enforcement quota
    """
    max_objects: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    Maximum object count - numeric value (alternate to MaxObjectsHum)
    """
    max_objects_hum: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    Maximum object count - human readable format (i.e. 10k) (alternate to MaxObjects)
    """
    max_size: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    Maximum size - numeric value (alternate to MaxSizeHum)
    """
    max_size_hum: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    Maximum size - human readable format (alternate to MaxSize)
    """

@pulumi.input_type
class QuotaArgsArgs:
    def __init__(__self__, *,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 max_objects: pulumi.Input[Optional[_builtins.int]] = None,
                 max_objects_hum: pulumi.Input[Optional[_builtins.str]] = None,
                 max_size: pulumi.Input[Optional[_builtins.int]] = None,
                 max_size_hum: pulumi.Input[Optional[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.bool] enabled: Enable or disable quota enforcement quota
        :param pulumi.Input[_builtins.int] max_objects: Maximum object count - numeric value (alternate to MaxObjectsHum)
        :param pulumi.Input[_builtins.str] max_objects_hum: Maximum object count - human readable format (i.e. 10k) (alternate to MaxObjects)
        :param pulumi.Input[_builtins.int] max_size: Maximum size - numeric value (alternate to MaxSizeHum)
        :param pulumi.Input[_builtins.str] max_size_hum: Maximum size - human readable format (alternate to MaxSize)
        """
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if max_objects is not None:
            pulumi.set(__self__, "max_objects", max_objects)
        if max_objects_hum is not None:
            pulumi.set(__self__, "max_objects_hum", max_objects_hum)
        if max_size is not None:
            pulumi.set(__self__, "max_size", max_size)
        if max_size_hum is not None:
            pulumi.set(__self__, "max_size_hum", max_size_hum)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Enable or disable quota enforcement quota
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="maxObjects")
    def max_objects(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Maximum object count - numeric value (alternate to MaxObjectsHum)
        """
        return pulumi.get(self, "max_objects")

    @max_objects.setter
    def max_objects(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "max_objects", value)

    @_builtins.property
    @pulumi.getter(name="maxObjectsHum")
    def max_objects_hum(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Maximum object count - human readable format (i.e. 10k) (alternate to MaxObjects)
        """
        return pulumi.get(self, "max_objects_hum")

    @max_objects_hum.setter
    def max_objects_hum(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "max_objects_hum", value)

    @_builtins.property
    @pulumi.getter(name="maxSize")
    def max_size(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Maximum size - numeric value (alternate to MaxSizeHum)
        """
        return pulumi.get(self, "max_size")

    @max_size.setter
    def max_size(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "max_size", value)

    @_builtins.property
    @pulumi.getter(name="maxSizeHum")
    def max_size_hum(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Maximum size - human readable format (alternate to MaxSize)
        """
        return pulumi.get(self, "max_size_hum")

    @max_size_hum.setter
    def max_size_hum(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "max_size_hum", value)


