# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._enums import *
from ._inputs import *

__all__ = ['UserArgs', 'User']

@pulumi.input_type
class UserArgs:
    def __init__(__self__, *,
                 user_id: pulumi.Input[_builtins.str],
                 capabilities: pulumi.Input[Optional['CapabilitiesArgs']] = None,
                 display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 email: pulumi.Input[Optional[_builtins.str]] = None,
                 max_buckets: pulumi.Input[Optional[_builtins.int]] = None,
                 suspended: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        The set of arguments for constructing a User resource.
        """
        pulumi.set(__self__, "user_id", user_id)
        if capabilities is not None:
            pulumi.set(__self__, "capabilities", capabilities)
        if display_name is not None:
            pulumi.set(__self__, "display_name", display_name)
        if email is not None:
            pulumi.set(__self__, "email", email)
        if max_buckets is not None:
            pulumi.set(__self__, "max_buckets", max_buckets)
        if suspended is not None:
            pulumi.set(__self__, "suspended", suspended)

    @_builtins.property
    @pulumi.getter(name="userId")
    def user_id(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "user_id")

    @user_id.setter
    def user_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "user_id", value)

    @_builtins.property
    @pulumi.getter
    def capabilities(self) -> pulumi.Input[Optional['CapabilitiesArgs']]:
        return pulumi.get(self, "capabilities")

    @capabilities.setter
    def capabilities(self, value: pulumi.Input[Optional['CapabilitiesArgs']]):
        pulumi.set(self, "capabilities", value)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter
    def email(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "email")

    @email.setter
    def email(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "email", value)

    @_builtins.property
    @pulumi.getter(name="maxBuckets")
    def max_buckets(self) -> pulumi.Input[Optional[_builtins.int]]:
        return pulumi.get(self, "max_buckets")

    @max_buckets.setter
    def max_buckets(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "max_buckets", value)

    @_builtins.property
    @pulumi.getter
    def suspended(self) -> pulumi.Input[Optional[_builtins.bool]]:
        return pulumi.get(self, "suspended")

    @suspended.setter
    def suspended(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "suspended", value)


@pulumi.type_token("ceph-radosgw:index:User")
class User(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 capabilities: pulumi.Input[Optional[Union['CapabilitiesArgs', 'CapabilitiesArgsDict']]] = None,
                 display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 email: pulumi.Input[Optional[_builtins.str]] = None,
                 max_buckets: pulumi.Input[Optional[_builtins.int]] = None,
                 suspended: pulumi.Input[Optional[_builtins.bool]] = None,
                 user_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a User resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: UserArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a User resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param UserArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(UserArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 capabilities: pulumi.Input[Optional[Union['CapabilitiesArgs', 'CapabilitiesArgsDict']]] = None,
                 display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 email: pulumi.Input[Optional[_builtins.str]] = None,
                 max_buckets: pulumi.Input[Optional[_builtins.int]] = None,
                 suspended: pulumi.Input[Optional[_builtins.bool]] = None,
                 user_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = UserArgs.__new__(UserArgs)

            __props__.__dict__["capabilities"] = capabilities
            __props__.__dict__["display_name"] = display_name
            __props__.__dict__["email"] = email
            __props__.__dict__["max_buckets"] = max_buckets
            __props__.__dict__["suspended"] = suspended
            if user_id is None and not opts.urn:
                raise TypeError("Missing required property 'user_id'")
            __props__.__dict__["user_id"] = user_id
            __props__.__dict__["_assimilated"] = None
            __props__.__dict__["keys"] = None
        super(User, __self__).__init__(
            'ceph-radosgw:index:User',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'User':
        """
        Get an existing User resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = UserArgs.__new__(UserArgs)

        __props__.__dict__["_assimilated"] = None
        __props__.__dict__["capabilities"] = None
        __props__.__dict__["display_name"] = None
        __props__.__dict__["email"] = None
        __props__.__dict__["keys"] = None
        __props__.__dict__["max_buckets"] = None
        __props__.__dict__["suspended"] = None
        __props__.__dict__["user_id"] = None
        return User(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def _assimilated(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "_assimilated")

    @_builtins.property
    @pulumi.getter
    def capabilities(self) -> pulumi.Output[Optional['outputs.Capabilities']]:
        return pulumi.get(self, "capabilities")

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "display_name")

    @_builtins.property
    @pulumi.getter
    def email(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "email")

    @_builtins.property
    @pulumi.getter
    def keys(self) -> pulumi.Output[Sequence['outputs.KeyEntry']]:
        return pulumi.get(self, "keys")

    @_builtins.property
    @pulumi.getter(name="maxBuckets")
    def max_buckets(self) -> pulumi.Output[Optional[_builtins.int]]:
        return pulumi.get(self, "max_buckets")

    @_builtins.property
    @pulumi.getter
    def suspended(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "suspended")

    @_builtins.property
    @pulumi.getter(name="userId")
    def user_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "user_id")

