// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.cephradosgw;

import com.osmitgmbh.cephradosgw.BucketArgs;
import com.osmitgmbh.cephradosgw.Utilities;
import com.osmitgmbh.cephradosgw.outputs.QuotaArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="ceph-radosgw:index:Bucket")
public class Bucket extends com.pulumi.resources.CustomResource {
    /**
     * Bucket was &#39;assimilated&#39; - managing an existing bucket.
     * 
     */
    @Export(name="_assimilated", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> _assimilated;

    /**
     * @return Bucket was &#39;assimilated&#39; - managing an existing bucket.
     * 
     */
    public Output<Boolean> _assimilated() {
        return this._assimilated;
    }
    @Export(name="_location", refs={String.class}, tree="[0]")
    private Output<String> _location;

    public Output<String> _location() {
        return this._location;
    }
    /**
     * Bucket name
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Bucket name
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Bucket object locking enabled
     * 
     */
    @Export(name="objectLocking", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> objectLocking;

    /**
     * @return Bucket object locking enabled
     * 
     */
    public Output<Optional<Boolean>> objectLocking() {
        return Codegen.optional(this.objectLocking);
    }
    /**
     * Purge bucket on delete.
     * 
     */
    @Export(name="purgeOnDelete", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> purgeOnDelete;

    /**
     * @return Purge bucket on delete.
     * 
     */
    public Output<Optional<Boolean>> purgeOnDelete() {
        return Codegen.optional(this.purgeOnDelete);
    }
    /**
     * Bucket quota configuration
     * 
     */
    @Export(name="quota", refs={QuotaArgs.class}, tree="[0]")
    private Output</* @Nullable */ QuotaArgs> quota;

    /**
     * @return Bucket quota configuration
     * 
     */
    public Output<Optional<QuotaArgs>> quota() {
        return Codegen.optional(this.quota);
    }
    /**
     * The unique bucket id.
     * 
     */
    @Export(name="ubid", refs={String.class}, tree="[0]")
    private Output<String> ubid;

    /**
     * @return The unique bucket id.
     * 
     */
    public Output<String> ubid() {
        return this.ubid;
    }
    @Export(name="versioning", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> versioning;

    public Output<Optional<Boolean>> versioning() {
        return Codegen.optional(this.versioning);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Bucket(java.lang.String name) {
        this(name, BucketArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Bucket(java.lang.String name, BucketArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Bucket(java.lang.String name, BucketArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("ceph-radosgw:index:Bucket", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Bucket(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("ceph-radosgw:index:Bucket", name, null, makeResourceOptions(options, id), false);
    }

    private static BucketArgs makeArgs(BucketArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? BucketArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Bucket get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Bucket(name, id, options);
    }
}
