// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.cephradosgw;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class BucketPolicyArgs extends com.pulumi.resources.ResourceArgs {

    public static final BucketPolicyArgs Empty = new BucketPolicyArgs();

    /**
     * Bucket name
     * 
     */
    @Import(name="bucket", required=true)
    private Output<String> bucket;

    /**
     * @return Bucket name
     * 
     */
    public Output<String> bucket() {
        return this.bucket;
    }

    /**
     * Bucket policy
     * 
     */
    @Import(name="policy", required=true)
    private Output<String> policy;

    /**
     * @return Bucket policy
     * 
     */
    public Output<String> policy() {
        return this.policy;
    }

    private BucketPolicyArgs() {}

    private BucketPolicyArgs(BucketPolicyArgs $) {
        this.bucket = $.bucket;
        this.policy = $.policy;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(BucketPolicyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private BucketPolicyArgs $;

        public Builder() {
            $ = new BucketPolicyArgs();
        }

        public Builder(BucketPolicyArgs defaults) {
            $ = new BucketPolicyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param bucket Bucket name
         * 
         * @return builder
         * 
         */
        public Builder bucket(Output<String> bucket) {
            $.bucket = bucket;
            return this;
        }

        /**
         * @param bucket Bucket name
         * 
         * @return builder
         * 
         */
        public Builder bucket(String bucket) {
            return bucket(Output.of(bucket));
        }

        /**
         * @param policy Bucket policy
         * 
         * @return builder
         * 
         */
        public Builder policy(Output<String> policy) {
            $.policy = policy;
            return this;
        }

        /**
         * @param policy Bucket policy
         * 
         * @return builder
         * 
         */
        public Builder policy(String policy) {
            return policy(Output.of(policy));
        }

        public BucketPolicyArgs build() {
            if ($.bucket == null) {
                throw new MissingRequiredPropertyException("BucketPolicyArgs", "bucket");
            }
            if ($.policy == null) {
                throw new MissingRequiredPropertyException("BucketPolicyArgs", "policy");
            }
            return $;
        }
    }

}
