// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.cephradosgw;

import com.osmitgmbh.cephradosgw.inputs.QuotaArgsArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class BucketArgs extends com.pulumi.resources.ResourceArgs {

    public static final BucketArgs Empty = new BucketArgs();

    /**
     * Bucket name
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Bucket name
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * Bucket object locking enabled
     * 
     */
    @Import(name="objectLocking")
    private @Nullable Output<Boolean> objectLocking;

    /**
     * @return Bucket object locking enabled
     * 
     */
    public Optional<Output<Boolean>> objectLocking() {
        return Optional.ofNullable(this.objectLocking);
    }

    /**
     * Purge bucket on delete
     * 
     */
    @Import(name="purgeOnDelete")
    private @Nullable Output<Boolean> purgeOnDelete;

    /**
     * @return Purge bucket on delete
     * 
     */
    public Optional<Output<Boolean>> purgeOnDelete() {
        return Optional.ofNullable(this.purgeOnDelete);
    }

    /**
     * Bucket quota configuration
     * 
     */
    @Import(name="quota")
    private @Nullable Output<QuotaArgsArgs> quota;

    /**
     * @return Bucket quota configuration
     * 
     */
    public Optional<Output<QuotaArgsArgs>> quota() {
        return Optional.ofNullable(this.quota);
    }

    @Import(name="versioning")
    private @Nullable Output<Boolean> versioning;

    public Optional<Output<Boolean>> versioning() {
        return Optional.ofNullable(this.versioning);
    }

    private BucketArgs() {}

    private BucketArgs(BucketArgs $) {
        this.name = $.name;
        this.objectLocking = $.objectLocking;
        this.purgeOnDelete = $.purgeOnDelete;
        this.quota = $.quota;
        this.versioning = $.versioning;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(BucketArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private BucketArgs $;

        public Builder() {
            $ = new BucketArgs();
        }

        public Builder(BucketArgs defaults) {
            $ = new BucketArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name Bucket name
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Bucket name
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param objectLocking Bucket object locking enabled
         * 
         * @return builder
         * 
         */
        public Builder objectLocking(@Nullable Output<Boolean> objectLocking) {
            $.objectLocking = objectLocking;
            return this;
        }

        /**
         * @param objectLocking Bucket object locking enabled
         * 
         * @return builder
         * 
         */
        public Builder objectLocking(Boolean objectLocking) {
            return objectLocking(Output.of(objectLocking));
        }

        /**
         * @param purgeOnDelete Purge bucket on delete
         * 
         * @return builder
         * 
         */
        public Builder purgeOnDelete(@Nullable Output<Boolean> purgeOnDelete) {
            $.purgeOnDelete = purgeOnDelete;
            return this;
        }

        /**
         * @param purgeOnDelete Purge bucket on delete
         * 
         * @return builder
         * 
         */
        public Builder purgeOnDelete(Boolean purgeOnDelete) {
            return purgeOnDelete(Output.of(purgeOnDelete));
        }

        /**
         * @param quota Bucket quota configuration
         * 
         * @return builder
         * 
         */
        public Builder quota(@Nullable Output<QuotaArgsArgs> quota) {
            $.quota = quota;
            return this;
        }

        /**
         * @param quota Bucket quota configuration
         * 
         * @return builder
         * 
         */
        public Builder quota(QuotaArgsArgs quota) {
            return quota(Output.of(quota));
        }

        public Builder versioning(@Nullable Output<Boolean> versioning) {
            $.versioning = versioning;
            return this;
        }

        public Builder versioning(Boolean versioning) {
            return versioning(Output.of(versioning));
        }

        public BucketArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("BucketArgs", "name");
            }
            return $;
        }
    }

}
