// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.cephradosgw;

import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("ceph-radosgw");
/**
 * The username. It&#39;s important but not secret.
 * 
 */
    public Optional<String> accessKeyID() {
        return Codegen.stringProp("accessKeyID").config(config).get();
    }
/**
 * Assimilate an existing object during create
 * 
 */
    public Optional<String> assimilate() {
        return Codegen.stringProp("assimilate").config(config).get();
    }
/**
 * Delete assimilated objects during delete (otherwise they would be kept on OpenZiti)
 * 
 */
    public Optional<String> deleteAssimilated() {
        return Codegen.stringProp("deleteAssimilated").config(config).get();
    }
/**
 * The URI to the API
 * 
 */
    public Optional<String> endpoint() {
        return Codegen.stringProp("endpoint").config(config).get();
    }
/**
 * Don&#39;t validate server SSL certificate
 * 
 */
    public Optional<String> insecure() {
        return Codegen.stringProp("insecure").config(config).get();
    }
/**
 * The password. It is very secret.
 * 
 */
    public Optional<String> secretAccessKey() {
        return Codegen.stringProp("secretAccessKey").config(config).get();
    }
}
