// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.cephradosgw;

import com.osmitgmbh.cephradosgw.KeyArgs;
import com.osmitgmbh.cephradosgw.Utilities;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="ceph-radosgw:index:Key")
public class Key extends com.pulumi.resources.CustomResource {
    @Export(name="_assimilated", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> _assimilated;

    public Output<Boolean> _assimilated() {
        return this._assimilated;
    }
    /**
     * The access key
     * 
     */
    @Export(name="accessKey", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> accessKey;

    /**
     * @return The access key
     * 
     */
    public Output<Optional<String>> accessKey() {
        return Codegen.optional(this.accessKey);
    }
    /**
     * key type - either &#39;s3&#39; or &#39;swift&#39;
     * 
     */
    @Export(name="keyType", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> keyType;

    /**
     * @return key type - either &#39;s3&#39; or &#39;swift&#39;
     * 
     */
    public Output<Optional<String>> keyType() {
        return Codegen.optional(this.keyType);
    }
    /**
     * The secret key
     * 
     */
    @Export(name="secretKey", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> secretKey;

    /**
     * @return The secret key
     * 
     */
    public Output<Optional<String>> secretKey() {
        return Codegen.optional(this.secretKey);
    }
    /**
     * Name of sub-user (optional)
     * 
     */
    @Export(name="subUserName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> subUserName;

    /**
     * @return Name of sub-user (optional)
     * 
     */
    public Output<Optional<String>> subUserName() {
        return Codegen.optional(this.subUserName);
    }
    /**
     * User-ID of &#39;parent&#39; user
     * 
     */
    @Export(name="userId", refs={String.class}, tree="[0]")
    private Output<String> userId;

    /**
     * @return User-ID of &#39;parent&#39; user
     * 
     */
    public Output<String> userId() {
        return this.userId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Key(java.lang.String name) {
        this(name, KeyArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Key(java.lang.String name, KeyArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Key(java.lang.String name, KeyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("ceph-radosgw:index:Key", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Key(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("ceph-radosgw:index:Key", name, null, makeResourceOptions(options, id), false);
    }

    private static KeyArgs makeArgs(KeyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? KeyArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Key get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Key(name, id, options);
    }
}
