// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.cephradosgw;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class KeyArgs extends com.pulumi.resources.ResourceArgs {

    public static final KeyArgs Empty = new KeyArgs();

    /**
     * The access key
     * 
     */
    @Import(name="accessKey")
    private @Nullable Output<String> accessKey;

    /**
     * @return The access key
     * 
     */
    public Optional<Output<String>> accessKey() {
        return Optional.ofNullable(this.accessKey);
    }

    /**
     * key type - either &#39;s3&#39; or &#39;swift&#39;
     * 
     */
    @Import(name="keyType")
    private @Nullable Output<String> keyType;

    /**
     * @return key type - either &#39;s3&#39; or &#39;swift&#39;
     * 
     */
    public Optional<Output<String>> keyType() {
        return Optional.ofNullable(this.keyType);
    }

    /**
     * The secret key
     * 
     */
    @Import(name="secretKey")
    private @Nullable Output<String> secretKey;

    /**
     * @return The secret key
     * 
     */
    public Optional<Output<String>> secretKey() {
        return Optional.ofNullable(this.secretKey);
    }

    /**
     * Name of sub-user (optional)
     * 
     */
    @Import(name="subUserName")
    private @Nullable Output<String> subUserName;

    /**
     * @return Name of sub-user (optional)
     * 
     */
    public Optional<Output<String>> subUserName() {
        return Optional.ofNullable(this.subUserName);
    }

    /**
     * User-ID of &#39;parent&#39; user
     * 
     */
    @Import(name="userId", required=true)
    private Output<String> userId;

    /**
     * @return User-ID of &#39;parent&#39; user
     * 
     */
    public Output<String> userId() {
        return this.userId;
    }

    private KeyArgs() {}

    private KeyArgs(KeyArgs $) {
        this.accessKey = $.accessKey;
        this.keyType = $.keyType;
        this.secretKey = $.secretKey;
        this.subUserName = $.subUserName;
        this.userId = $.userId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(KeyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private KeyArgs $;

        public Builder() {
            $ = new KeyArgs();
        }

        public Builder(KeyArgs defaults) {
            $ = new KeyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accessKey The access key
         * 
         * @return builder
         * 
         */
        public Builder accessKey(@Nullable Output<String> accessKey) {
            $.accessKey = accessKey;
            return this;
        }

        /**
         * @param accessKey The access key
         * 
         * @return builder
         * 
         */
        public Builder accessKey(String accessKey) {
            return accessKey(Output.of(accessKey));
        }

        /**
         * @param keyType key type - either &#39;s3&#39; or &#39;swift&#39;
         * 
         * @return builder
         * 
         */
        public Builder keyType(@Nullable Output<String> keyType) {
            $.keyType = keyType;
            return this;
        }

        /**
         * @param keyType key type - either &#39;s3&#39; or &#39;swift&#39;
         * 
         * @return builder
         * 
         */
        public Builder keyType(String keyType) {
            return keyType(Output.of(keyType));
        }

        /**
         * @param secretKey The secret key
         * 
         * @return builder
         * 
         */
        public Builder secretKey(@Nullable Output<String> secretKey) {
            $.secretKey = secretKey;
            return this;
        }

        /**
         * @param secretKey The secret key
         * 
         * @return builder
         * 
         */
        public Builder secretKey(String secretKey) {
            return secretKey(Output.of(secretKey));
        }

        /**
         * @param subUserName Name of sub-user (optional)
         * 
         * @return builder
         * 
         */
        public Builder subUserName(@Nullable Output<String> subUserName) {
            $.subUserName = subUserName;
            return this;
        }

        /**
         * @param subUserName Name of sub-user (optional)
         * 
         * @return builder
         * 
         */
        public Builder subUserName(String subUserName) {
            return subUserName(Output.of(subUserName));
        }

        /**
         * @param userId User-ID of &#39;parent&#39; user
         * 
         * @return builder
         * 
         */
        public Builder userId(Output<String> userId) {
            $.userId = userId;
            return this;
        }

        /**
         * @param userId User-ID of &#39;parent&#39; user
         * 
         * @return builder
         * 
         */
        public Builder userId(String userId) {
            return userId(Output.of(userId));
        }

        public KeyArgs build() {
            if ($.userId == null) {
                throw new MissingRequiredPropertyException("KeyArgs", "userId");
            }
            return $;
        }
    }

}
