// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.cephradosgw;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProviderArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProviderArgs Empty = new ProviderArgs();

    /**
     * The username. It&#39;s important but not secret.
     * 
     */
    @Import(name="accessKeyID")
    private @Nullable Output<String> accessKeyID;

    /**
     * @return The username. It&#39;s important but not secret.
     * 
     */
    public Optional<Output<String>> accessKeyID() {
        return Optional.ofNullable(this.accessKeyID);
    }

    /**
     * Assimilate an existing object during create
     * 
     */
    @Import(name="assimilate")
    private @Nullable Output<String> assimilate;

    /**
     * @return Assimilate an existing object during create
     * 
     */
    public Optional<Output<String>> assimilate() {
        return Optional.ofNullable(this.assimilate);
    }

    /**
     * Delete assimilated objects during delete (otherwise they would be kept on OpenZiti)
     * 
     */
    @Import(name="deleteAssimilated")
    private @Nullable Output<String> deleteAssimilated;

    /**
     * @return Delete assimilated objects during delete (otherwise they would be kept on OpenZiti)
     * 
     */
    public Optional<Output<String>> deleteAssimilated() {
        return Optional.ofNullable(this.deleteAssimilated);
    }

    /**
     * The URI to the API
     * 
     */
    @Import(name="endpoint")
    private @Nullable Output<String> endpoint;

    /**
     * @return The URI to the API
     * 
     */
    public Optional<Output<String>> endpoint() {
        return Optional.ofNullable(this.endpoint);
    }

    /**
     * Don&#39;t validate server SSL certificate
     * 
     */
    @Import(name="insecure")
    private @Nullable Output<String> insecure;

    /**
     * @return Don&#39;t validate server SSL certificate
     * 
     */
    public Optional<Output<String>> insecure() {
        return Optional.ofNullable(this.insecure);
    }

    /**
     * The password. It is very secret.
     * 
     */
    @Import(name="secretAccessKey")
    private @Nullable Output<String> secretAccessKey;

    /**
     * @return The password. It is very secret.
     * 
     */
    public Optional<Output<String>> secretAccessKey() {
        return Optional.ofNullable(this.secretAccessKey);
    }

    private ProviderArgs() {}

    private ProviderArgs(ProviderArgs $) {
        this.accessKeyID = $.accessKeyID;
        this.assimilate = $.assimilate;
        this.deleteAssimilated = $.deleteAssimilated;
        this.endpoint = $.endpoint;
        this.insecure = $.insecure;
        this.secretAccessKey = $.secretAccessKey;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProviderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProviderArgs $;

        public Builder() {
            $ = new ProviderArgs();
        }

        public Builder(ProviderArgs defaults) {
            $ = new ProviderArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accessKeyID The username. It&#39;s important but not secret.
         * 
         * @return builder
         * 
         */
        public Builder accessKeyID(@Nullable Output<String> accessKeyID) {
            $.accessKeyID = accessKeyID;
            return this;
        }

        /**
         * @param accessKeyID The username. It&#39;s important but not secret.
         * 
         * @return builder
         * 
         */
        public Builder accessKeyID(String accessKeyID) {
            return accessKeyID(Output.of(accessKeyID));
        }

        /**
         * @param assimilate Assimilate an existing object during create
         * 
         * @return builder
         * 
         */
        public Builder assimilate(@Nullable Output<String> assimilate) {
            $.assimilate = assimilate;
            return this;
        }

        /**
         * @param assimilate Assimilate an existing object during create
         * 
         * @return builder
         * 
         */
        public Builder assimilate(String assimilate) {
            return assimilate(Output.of(assimilate));
        }

        /**
         * @param deleteAssimilated Delete assimilated objects during delete (otherwise they would be kept on OpenZiti)
         * 
         * @return builder
         * 
         */
        public Builder deleteAssimilated(@Nullable Output<String> deleteAssimilated) {
            $.deleteAssimilated = deleteAssimilated;
            return this;
        }

        /**
         * @param deleteAssimilated Delete assimilated objects during delete (otherwise they would be kept on OpenZiti)
         * 
         * @return builder
         * 
         */
        public Builder deleteAssimilated(String deleteAssimilated) {
            return deleteAssimilated(Output.of(deleteAssimilated));
        }

        /**
         * @param endpoint The URI to the API
         * 
         * @return builder
         * 
         */
        public Builder endpoint(@Nullable Output<String> endpoint) {
            $.endpoint = endpoint;
            return this;
        }

        /**
         * @param endpoint The URI to the API
         * 
         * @return builder
         * 
         */
        public Builder endpoint(String endpoint) {
            return endpoint(Output.of(endpoint));
        }

        /**
         * @param insecure Don&#39;t validate server SSL certificate
         * 
         * @return builder
         * 
         */
        public Builder insecure(@Nullable Output<String> insecure) {
            $.insecure = insecure;
            return this;
        }

        /**
         * @param insecure Don&#39;t validate server SSL certificate
         * 
         * @return builder
         * 
         */
        public Builder insecure(String insecure) {
            return insecure(Output.of(insecure));
        }

        /**
         * @param secretAccessKey The password. It is very secret.
         * 
         * @return builder
         * 
         */
        public Builder secretAccessKey(@Nullable Output<String> secretAccessKey) {
            $.secretAccessKey = secretAccessKey;
            return this;
        }

        /**
         * @param secretAccessKey The password. It is very secret.
         * 
         * @return builder
         * 
         */
        public Builder secretAccessKey(String secretAccessKey) {
            return secretAccessKey(Output.of(secretAccessKey));
        }

        public ProviderArgs build() {
            return $;
        }
    }

}
