// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.cephradosgw;

import com.osmitgmbh.cephradosgw.enums.KeyType;
import com.osmitgmbh.cephradosgw.enums.SubUserPermission;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SubUserArgs extends com.pulumi.resources.ResourceArgs {

    public static final SubUserArgs Empty = new SubUserArgs();

    @Import(name="generateKey")
    private @Nullable Output<Boolean> generateKey;

    public Optional<Output<Boolean>> generateKey() {
        return Optional.ofNullable(this.generateKey);
    }

    @Import(name="keyType")
    private @Nullable Output<KeyType> keyType;

    public Optional<Output<KeyType>> keyType() {
        return Optional.ofNullable(this.keyType);
    }

    @Import(name="permissions", required=true)
    private Output<SubUserPermission> permissions;

    public Output<SubUserPermission> permissions() {
        return this.permissions;
    }

    @Import(name="purgeKeys")
    private @Nullable Output<Boolean> purgeKeys;

    public Optional<Output<Boolean>> purgeKeys() {
        return Optional.ofNullable(this.purgeKeys);
    }

    @Import(name="secretKey")
    private @Nullable Output<String> secretKey;

    public Optional<Output<String>> secretKey() {
        return Optional.ofNullable(this.secretKey);
    }

    /**
     * Name of this subuser
     * 
     */
    @Import(name="subUserName", required=true)
    private Output<String> subUserName;

    /**
     * @return Name of this subuser
     * 
     */
    public Output<String> subUserName() {
        return this.subUserName;
    }

    /**
     * User-ID of &#39;parent&#39; user
     * 
     */
    @Import(name="userId", required=true)
    private Output<String> userId;

    /**
     * @return User-ID of &#39;parent&#39; user
     * 
     */
    public Output<String> userId() {
        return this.userId;
    }

    private SubUserArgs() {}

    private SubUserArgs(SubUserArgs $) {
        this.generateKey = $.generateKey;
        this.keyType = $.keyType;
        this.permissions = $.permissions;
        this.purgeKeys = $.purgeKeys;
        this.secretKey = $.secretKey;
        this.subUserName = $.subUserName;
        this.userId = $.userId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SubUserArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SubUserArgs $;

        public Builder() {
            $ = new SubUserArgs();
        }

        public Builder(SubUserArgs defaults) {
            $ = new SubUserArgs(Objects.requireNonNull(defaults));
        }

        public Builder generateKey(@Nullable Output<Boolean> generateKey) {
            $.generateKey = generateKey;
            return this;
        }

        public Builder generateKey(Boolean generateKey) {
            return generateKey(Output.of(generateKey));
        }

        public Builder keyType(@Nullable Output<KeyType> keyType) {
            $.keyType = keyType;
            return this;
        }

        public Builder keyType(KeyType keyType) {
            return keyType(Output.of(keyType));
        }

        public Builder permissions(Output<SubUserPermission> permissions) {
            $.permissions = permissions;
            return this;
        }

        public Builder permissions(SubUserPermission permissions) {
            return permissions(Output.of(permissions));
        }

        public Builder purgeKeys(@Nullable Output<Boolean> purgeKeys) {
            $.purgeKeys = purgeKeys;
            return this;
        }

        public Builder purgeKeys(Boolean purgeKeys) {
            return purgeKeys(Output.of(purgeKeys));
        }

        public Builder secretKey(@Nullable Output<String> secretKey) {
            $.secretKey = secretKey;
            return this;
        }

        public Builder secretKey(String secretKey) {
            return secretKey(Output.of(secretKey));
        }

        /**
         * @param subUserName Name of this subuser
         * 
         * @return builder
         * 
         */
        public Builder subUserName(Output<String> subUserName) {
            $.subUserName = subUserName;
            return this;
        }

        /**
         * @param subUserName Name of this subuser
         * 
         * @return builder
         * 
         */
        public Builder subUserName(String subUserName) {
            return subUserName(Output.of(subUserName));
        }

        /**
         * @param userId User-ID of &#39;parent&#39; user
         * 
         * @return builder
         * 
         */
        public Builder userId(Output<String> userId) {
            $.userId = userId;
            return this;
        }

        /**
         * @param userId User-ID of &#39;parent&#39; user
         * 
         * @return builder
         * 
         */
        public Builder userId(String userId) {
            return userId(Output.of(userId));
        }

        public SubUserArgs build() {
            if ($.permissions == null) {
                throw new MissingRequiredPropertyException("SubUserArgs", "permissions");
            }
            if ($.subUserName == null) {
                throw new MissingRequiredPropertyException("SubUserArgs", "subUserName");
            }
            if ($.userId == null) {
                throw new MissingRequiredPropertyException("SubUserArgs", "userId");
            }
            return $;
        }
    }

}
