// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.cephradosgw;

import com.osmitgmbh.cephradosgw.SubUserArgs;
import com.osmitgmbh.cephradosgw.Utilities;
import com.osmitgmbh.cephradosgw.enums.KeyType;
import com.osmitgmbh.cephradosgw.enums.SubUserPermission;
import com.osmitgmbh.cephradosgw.outputs.KeyEntry;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="ceph-radosgw:index:SubUser")
public class SubUser extends com.pulumi.resources.CustomResource {
    @Export(name="_assimilated", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> _assimilated;

    public Output<Boolean> _assimilated() {
        return this._assimilated;
    }
    @Export(name="fullname", refs={String.class}, tree="[0]")
    private Output<String> fullname;

    public Output<String> fullname() {
        return this.fullname;
    }
    @Export(name="generateKey", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> generateKey;

    public Output<Optional<Boolean>> generateKey() {
        return Codegen.optional(this.generateKey);
    }
    @Export(name="keyType", refs={KeyType.class}, tree="[0]")
    private Output</* @Nullable */ KeyType> keyType;

    public Output<Optional<KeyType>> keyType() {
        return Codegen.optional(this.keyType);
    }
    @Export(name="keys", refs={List.class,KeyEntry.class}, tree="[0,1]")
    private Output<List<KeyEntry>> keys;

    public Output<List<KeyEntry>> keys() {
        return this.keys;
    }
    @Export(name="permissions", refs={SubUserPermission.class}, tree="[0]")
    private Output<SubUserPermission> permissions;

    public Output<SubUserPermission> permissions() {
        return this.permissions;
    }
    @Export(name="purgeKeys", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> purgeKeys;

    public Output<Optional<Boolean>> purgeKeys() {
        return Codegen.optional(this.purgeKeys);
    }
    @Export(name="secretKey", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> secretKey;

    public Output<Optional<String>> secretKey() {
        return Codegen.optional(this.secretKey);
    }
    /**
     * Name of this subuser
     * 
     */
    @Export(name="subUserName", refs={String.class}, tree="[0]")
    private Output<String> subUserName;

    /**
     * @return Name of this subuser
     * 
     */
    public Output<String> subUserName() {
        return this.subUserName;
    }
    /**
     * User-ID of &#39;parent&#39; user
     * 
     */
    @Export(name="userId", refs={String.class}, tree="[0]")
    private Output<String> userId;

    /**
     * @return User-ID of &#39;parent&#39; user
     * 
     */
    public Output<String> userId() {
        return this.userId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public SubUser(java.lang.String name) {
        this(name, SubUserArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public SubUser(java.lang.String name, SubUserArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public SubUser(java.lang.String name, SubUserArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("ceph-radosgw:index:SubUser", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private SubUser(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("ceph-radosgw:index:SubUser", name, null, makeResourceOptions(options, id), false);
    }

    private static SubUserArgs makeArgs(SubUserArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? SubUserArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "secretKey"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static SubUser get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new SubUser(name, id, options);
    }
}
