// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.cephradosgw;

import com.osmitgmbh.cephradosgw.UserArgs;
import com.osmitgmbh.cephradosgw.Utilities;
import com.osmitgmbh.cephradosgw.outputs.Capabilities;
import com.osmitgmbh.cephradosgw.outputs.KeyEntry;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="ceph-radosgw:index:User")
public class User extends com.pulumi.resources.CustomResource {
    @Export(name="_assimilated", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> _assimilated;

    public Output<Boolean> _assimilated() {
        return this._assimilated;
    }
    @Export(name="capabilities", refs={Capabilities.class}, tree="[0]")
    private Output</* @Nullable */ Capabilities> capabilities;

    public Output<Optional<Capabilities>> capabilities() {
        return Codegen.optional(this.capabilities);
    }
    @Export(name="displayName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> displayName;

    public Output<Optional<String>> displayName() {
        return Codegen.optional(this.displayName);
    }
    @Export(name="email", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> email;

    public Output<Optional<String>> email() {
        return Codegen.optional(this.email);
    }
    @Export(name="keys", refs={List.class,KeyEntry.class}, tree="[0,1]")
    private Output<List<KeyEntry>> keys;

    public Output<List<KeyEntry>> keys() {
        return this.keys;
    }
    @Export(name="maxBuckets", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> maxBuckets;

    public Output<Optional<Integer>> maxBuckets() {
        return Codegen.optional(this.maxBuckets);
    }
    @Export(name="suspended", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> suspended;

    public Output<Optional<Boolean>> suspended() {
        return Codegen.optional(this.suspended);
    }
    @Export(name="userId", refs={String.class}, tree="[0]")
    private Output<String> userId;

    public Output<String> userId() {
        return this.userId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public User(java.lang.String name) {
        this(name, UserArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public User(java.lang.String name, UserArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public User(java.lang.String name, UserArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("ceph-radosgw:index:User", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private User(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("ceph-radosgw:index:User", name, null, makeResourceOptions(options, id), false);
    }

    private static UserArgs makeArgs(UserArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? UserArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static User get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new User(name, id, options);
    }
}
