// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.cephradosgw;

import com.osmitgmbh.cephradosgw.inputs.CapabilitiesArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class UserArgs extends com.pulumi.resources.ResourceArgs {

    public static final UserArgs Empty = new UserArgs();

    @Import(name="capabilities")
    private @Nullable Output<CapabilitiesArgs> capabilities;

    public Optional<Output<CapabilitiesArgs>> capabilities() {
        return Optional.ofNullable(this.capabilities);
    }

    @Import(name="displayName")
    private @Nullable Output<String> displayName;

    public Optional<Output<String>> displayName() {
        return Optional.ofNullable(this.displayName);
    }

    @Import(name="email")
    private @Nullable Output<String> email;

    public Optional<Output<String>> email() {
        return Optional.ofNullable(this.email);
    }

    @Import(name="maxBuckets")
    private @Nullable Output<Integer> maxBuckets;

    public Optional<Output<Integer>> maxBuckets() {
        return Optional.ofNullable(this.maxBuckets);
    }

    @Import(name="suspended")
    private @Nullable Output<Boolean> suspended;

    public Optional<Output<Boolean>> suspended() {
        return Optional.ofNullable(this.suspended);
    }

    @Import(name="userId", required=true)
    private Output<String> userId;

    public Output<String> userId() {
        return this.userId;
    }

    private UserArgs() {}

    private UserArgs(UserArgs $) {
        this.capabilities = $.capabilities;
        this.displayName = $.displayName;
        this.email = $.email;
        this.maxBuckets = $.maxBuckets;
        this.suspended = $.suspended;
        this.userId = $.userId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(UserArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private UserArgs $;

        public Builder() {
            $ = new UserArgs();
        }

        public Builder(UserArgs defaults) {
            $ = new UserArgs(Objects.requireNonNull(defaults));
        }

        public Builder capabilities(@Nullable Output<CapabilitiesArgs> capabilities) {
            $.capabilities = capabilities;
            return this;
        }

        public Builder capabilities(CapabilitiesArgs capabilities) {
            return capabilities(Output.of(capabilities));
        }

        public Builder displayName(@Nullable Output<String> displayName) {
            $.displayName = displayName;
            return this;
        }

        public Builder displayName(String displayName) {
            return displayName(Output.of(displayName));
        }

        public Builder email(@Nullable Output<String> email) {
            $.email = email;
            return this;
        }

        public Builder email(String email) {
            return email(Output.of(email));
        }

        public Builder maxBuckets(@Nullable Output<Integer> maxBuckets) {
            $.maxBuckets = maxBuckets;
            return this;
        }

        public Builder maxBuckets(Integer maxBuckets) {
            return maxBuckets(Output.of(maxBuckets));
        }

        public Builder suspended(@Nullable Output<Boolean> suspended) {
            $.suspended = suspended;
            return this;
        }

        public Builder suspended(Boolean suspended) {
            return suspended(Output.of(suspended));
        }

        public Builder userId(Output<String> userId) {
            $.userId = userId;
            return this;
        }

        public Builder userId(String userId) {
            return userId(Output.of(userId));
        }

        public UserArgs build() {
            if ($.userId == null) {
                throw new MissingRequiredPropertyException("UserArgs", "userId");
            }
            return $;
        }
    }

}
