// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.cephradosgw.enums;

import com.pulumi.core.annotations.EnumType;
import java.lang.String;
import java.util.Objects;
import java.util.StringJoiner;

    @EnumType
    public enum SubUserPermission {
        None("none"),
        Read("read"),
        Write("write"),
        ReadWrite("readWrite"),
        FullControl("fullControl");

        private final String value;

        SubUserPermission(String value) {
            this.value = Objects.requireNonNull(value);
        }

        @EnumType.Converter
        public String getValue() {
            return this.value;
        }

        @Override
        public java.lang.String toString() {
            return new StringJoiner(", ", "SubUserPermission[", "]")
                .add("value='" + this.value + "'")
                .toString();
        }
    }
