// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const CapabilityPermission = {
    Read: "read",
    Write: "write",
    Asterisk: "*",
} as const;

export type CapabilityPermission = (typeof CapabilityPermission)[keyof typeof CapabilityPermission];

export const KeyType = {
    S3: "s3",
    Swift: "swift",
} as const;

export type KeyType = (typeof KeyType)[keyof typeof KeyType];

export const SubUserPermission = {
    None: "none",
    Read: "read",
    Write: "write",
    ReadWrite: "readWrite",
    FullControl: "fullControl",
} as const;

export type SubUserPermission = (typeof SubUserPermission)[keyof typeof SubUserPermission];
