// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace OsmitGmbh.CephRadosgw.Outputs
{

    [OutputType]
    public sealed class Capabilities
    {
        public readonly OsmitGmbh.CephRadosgw.CapabilityPermission? AmzCache;
        public readonly OsmitGmbh.CephRadosgw.CapabilityPermission? Bilog;
        public readonly OsmitGmbh.CephRadosgw.CapabilityPermission? Buckets;
        public readonly OsmitGmbh.CephRadosgw.CapabilityPermission? Datalog;
        public readonly OsmitGmbh.CephRadosgw.CapabilityPermission? Info;
        public readonly OsmitGmbh.CephRadosgw.CapabilityPermission? Mdlog;
        public readonly OsmitGmbh.CephRadosgw.CapabilityPermission? Metadata;
        public readonly OsmitGmbh.CephRadosgw.CapabilityPermission? OidcProvider;
        public readonly OsmitGmbh.CephRadosgw.CapabilityPermission? Ratelimit;
        public readonly OsmitGmbh.CephRadosgw.CapabilityPermission? Roles;
        public readonly OsmitGmbh.CephRadosgw.CapabilityPermission? Usage;
        public readonly OsmitGmbh.CephRadosgw.CapabilityPermission? UserPolicy;
        public readonly OsmitGmbh.CephRadosgw.CapabilityPermission? Users;
        public readonly OsmitGmbh.CephRadosgw.CapabilityPermission? Zone;

        [OutputConstructor]
        private Capabilities(
            OsmitGmbh.CephRadosgw.CapabilityPermission? amzCache,

            OsmitGmbh.CephRadosgw.CapabilityPermission? bilog,

            OsmitGmbh.CephRadosgw.CapabilityPermission? buckets,

            OsmitGmbh.CephRadosgw.CapabilityPermission? datalog,

            OsmitGmbh.CephRadosgw.CapabilityPermission? info,

            OsmitGmbh.CephRadosgw.CapabilityPermission? mdlog,

            OsmitGmbh.CephRadosgw.CapabilityPermission? metadata,

            OsmitGmbh.CephRadosgw.CapabilityPermission? oidcProvider,

            OsmitGmbh.CephRadosgw.CapabilityPermission? ratelimit,

            OsmitGmbh.CephRadosgw.CapabilityPermission? roles,

            OsmitGmbh.CephRadosgw.CapabilityPermission? usage,

            OsmitGmbh.CephRadosgw.CapabilityPermission? userPolicy,

            OsmitGmbh.CephRadosgw.CapabilityPermission? users,

            OsmitGmbh.CephRadosgw.CapabilityPermission? zone)
        {
            AmzCache = amzCache;
            Bilog = bilog;
            Buckets = buckets;
            Datalog = datalog;
            Info = info;
            Mdlog = mdlog;
            Metadata = metadata;
            OidcProvider = oidcProvider;
            Ratelimit = ratelimit;
            Roles = roles;
            Usage = usage;
            UserPolicy = userPolicy;
            Users = users;
            Zone = zone;
        }
    }
}
