// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CephRadosgw.Outputs
{

    [OutputType]
    public sealed class QuotaArgs
    {
        /// <summary>
        /// Enable or disable quota enforcement quota
        /// </summary>
        public readonly bool? Enabled;
        /// <summary>
        /// Maximum object count - numeric value (alternate to MaxObjectsHum)
        /// </summary>
        public readonly int? MaxObjects;
        /// <summary>
        /// Maximum object count - human readable format (i.e. 10k) (alternate to MaxObjects)
        /// </summary>
        public readonly string? MaxObjectsHum;
        /// <summary>
        /// Maximum size - numeric value (alternate to MaxSizeHum)
        /// </summary>
        public readonly int? MaxSize;
        /// <summary>
        /// Maximum size - human readable format (alternate to MaxSize)
        /// </summary>
        public readonly string? MaxSizeHum;

        [OutputConstructor]
        private QuotaArgs(
            bool? enabled,

            int? maxObjects,

            string? maxObjectsHum,

            int? maxSize,

            string? maxSizeHum)
        {
            Enabled = enabled;
            MaxObjects = maxObjects;
            MaxObjectsHum = maxObjectsHum;
            MaxSize = maxSize;
            MaxSizeHum = maxSizeHum;
        }
    }
}
