// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"internal"
)

var _ = internal.GetEnvOrDefault

// The username. It's important but not secret.
func GetAccessKeyID(ctx *pulumi.Context) string {
	return config.Get(ctx, "ceph-radosgw:accessKeyID")
}

// Assimilate an existing object during create
func GetAssimilate(ctx *pulumi.Context) string {
	return config.Get(ctx, "ceph-radosgw:assimilate")
}

// Delete assimilated objects during delete (otherwise they would be kept on OpenZiti)
func GetDeleteAssimilated(ctx *pulumi.Context) string {
	return config.Get(ctx, "ceph-radosgw:deleteAssimilated")
}

// The URI to the API
func GetEndpoint(ctx *pulumi.Context) string {
	return config.Get(ctx, "ceph-radosgw:endpoint")
}

// The password. It is very secret.
func GetSecretAccessKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "ceph-radosgw:secretAccessKey")
}
func GetVersion(ctx *pulumi.Context) string {
	return config.Get(ctx, "ceph-radosgw:version")
}
