# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('ceph-radosgw')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def access_key_id(self) -> Optional[str]:
        """
        The username. It's important but not secret.
        """
        return __config__.get('accessKeyID')

    @_builtins.property
    def assimilate(self) -> Optional[str]:
        """
        Assimilate an existing object during create
        """
        return __config__.get('assimilate')

    @_builtins.property
    def delete_assimilated(self) -> Optional[str]:
        """
        Delete assimilated objects during delete (otherwise they would be kept on OpenZiti)
        """
        return __config__.get('deleteAssimilated')

    @_builtins.property
    def endpoint(self) -> Optional[str]:
        """
        The URI to the API
        """
        return __config__.get('endpoint')

    @_builtins.property
    def insecure(self) -> Optional[str]:
        """
        Don't validate server SSL certificate
        """
        return __config__.get('insecure')

    @_builtins.property
    def secret_access_key(self) -> Optional[str]:
        """
        The password. It is very secret.
        """
        return __config__.get('secretAccessKey')

