// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.cephradosgw.inputs;

import com.osmitgmbh.cephradosgw.enums.CapabilityPermission;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CapabilitiesArgs extends com.pulumi.resources.ResourceArgs {

    public static final CapabilitiesArgs Empty = new CapabilitiesArgs();

    @Import(name="amzCache")
    private @Nullable Output<CapabilityPermission> amzCache;

    public Optional<Output<CapabilityPermission>> amzCache() {
        return Optional.ofNullable(this.amzCache);
    }

    @Import(name="bilog")
    private @Nullable Output<CapabilityPermission> bilog;

    public Optional<Output<CapabilityPermission>> bilog() {
        return Optional.ofNullable(this.bilog);
    }

    @Import(name="buckets")
    private @Nullable Output<CapabilityPermission> buckets;

    public Optional<Output<CapabilityPermission>> buckets() {
        return Optional.ofNullable(this.buckets);
    }

    @Import(name="datalog")
    private @Nullable Output<CapabilityPermission> datalog;

    public Optional<Output<CapabilityPermission>> datalog() {
        return Optional.ofNullable(this.datalog);
    }

    @Import(name="info")
    private @Nullable Output<CapabilityPermission> info;

    public Optional<Output<CapabilityPermission>> info() {
        return Optional.ofNullable(this.info);
    }

    @Import(name="mdlog")
    private @Nullable Output<CapabilityPermission> mdlog;

    public Optional<Output<CapabilityPermission>> mdlog() {
        return Optional.ofNullable(this.mdlog);
    }

    @Import(name="metadata")
    private @Nullable Output<CapabilityPermission> metadata;

    public Optional<Output<CapabilityPermission>> metadata() {
        return Optional.ofNullable(this.metadata);
    }

    @Import(name="oidcProvider")
    private @Nullable Output<CapabilityPermission> oidcProvider;

    public Optional<Output<CapabilityPermission>> oidcProvider() {
        return Optional.ofNullable(this.oidcProvider);
    }

    @Import(name="ratelimit")
    private @Nullable Output<CapabilityPermission> ratelimit;

    public Optional<Output<CapabilityPermission>> ratelimit() {
        return Optional.ofNullable(this.ratelimit);
    }

    @Import(name="roles")
    private @Nullable Output<CapabilityPermission> roles;

    public Optional<Output<CapabilityPermission>> roles() {
        return Optional.ofNullable(this.roles);
    }

    @Import(name="usage")
    private @Nullable Output<CapabilityPermission> usage;

    public Optional<Output<CapabilityPermission>> usage() {
        return Optional.ofNullable(this.usage);
    }

    @Import(name="userPolicy")
    private @Nullable Output<CapabilityPermission> userPolicy;

    public Optional<Output<CapabilityPermission>> userPolicy() {
        return Optional.ofNullable(this.userPolicy);
    }

    @Import(name="users")
    private @Nullable Output<CapabilityPermission> users;

    public Optional<Output<CapabilityPermission>> users() {
        return Optional.ofNullable(this.users);
    }

    @Import(name="zone")
    private @Nullable Output<CapabilityPermission> zone;

    public Optional<Output<CapabilityPermission>> zone() {
        return Optional.ofNullable(this.zone);
    }

    private CapabilitiesArgs() {}

    private CapabilitiesArgs(CapabilitiesArgs $) {
        this.amzCache = $.amzCache;
        this.bilog = $.bilog;
        this.buckets = $.buckets;
        this.datalog = $.datalog;
        this.info = $.info;
        this.mdlog = $.mdlog;
        this.metadata = $.metadata;
        this.oidcProvider = $.oidcProvider;
        this.ratelimit = $.ratelimit;
        this.roles = $.roles;
        this.usage = $.usage;
        this.userPolicy = $.userPolicy;
        this.users = $.users;
        this.zone = $.zone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CapabilitiesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CapabilitiesArgs $;

        public Builder() {
            $ = new CapabilitiesArgs();
        }

        public Builder(CapabilitiesArgs defaults) {
            $ = new CapabilitiesArgs(Objects.requireNonNull(defaults));
        }

        public Builder amzCache(@Nullable Output<CapabilityPermission> amzCache) {
            $.amzCache = amzCache;
            return this;
        }

        public Builder amzCache(CapabilityPermission amzCache) {
            return amzCache(Output.of(amzCache));
        }

        public Builder bilog(@Nullable Output<CapabilityPermission> bilog) {
            $.bilog = bilog;
            return this;
        }

        public Builder bilog(CapabilityPermission bilog) {
            return bilog(Output.of(bilog));
        }

        public Builder buckets(@Nullable Output<CapabilityPermission> buckets) {
            $.buckets = buckets;
            return this;
        }

        public Builder buckets(CapabilityPermission buckets) {
            return buckets(Output.of(buckets));
        }

        public Builder datalog(@Nullable Output<CapabilityPermission> datalog) {
            $.datalog = datalog;
            return this;
        }

        public Builder datalog(CapabilityPermission datalog) {
            return datalog(Output.of(datalog));
        }

        public Builder info(@Nullable Output<CapabilityPermission> info) {
            $.info = info;
            return this;
        }

        public Builder info(CapabilityPermission info) {
            return info(Output.of(info));
        }

        public Builder mdlog(@Nullable Output<CapabilityPermission> mdlog) {
            $.mdlog = mdlog;
            return this;
        }

        public Builder mdlog(CapabilityPermission mdlog) {
            return mdlog(Output.of(mdlog));
        }

        public Builder metadata(@Nullable Output<CapabilityPermission> metadata) {
            $.metadata = metadata;
            return this;
        }

        public Builder metadata(CapabilityPermission metadata) {
            return metadata(Output.of(metadata));
        }

        public Builder oidcProvider(@Nullable Output<CapabilityPermission> oidcProvider) {
            $.oidcProvider = oidcProvider;
            return this;
        }

        public Builder oidcProvider(CapabilityPermission oidcProvider) {
            return oidcProvider(Output.of(oidcProvider));
        }

        public Builder ratelimit(@Nullable Output<CapabilityPermission> ratelimit) {
            $.ratelimit = ratelimit;
            return this;
        }

        public Builder ratelimit(CapabilityPermission ratelimit) {
            return ratelimit(Output.of(ratelimit));
        }

        public Builder roles(@Nullable Output<CapabilityPermission> roles) {
            $.roles = roles;
            return this;
        }

        public Builder roles(CapabilityPermission roles) {
            return roles(Output.of(roles));
        }

        public Builder usage(@Nullable Output<CapabilityPermission> usage) {
            $.usage = usage;
            return this;
        }

        public Builder usage(CapabilityPermission usage) {
            return usage(Output.of(usage));
        }

        public Builder userPolicy(@Nullable Output<CapabilityPermission> userPolicy) {
            $.userPolicy = userPolicy;
            return this;
        }

        public Builder userPolicy(CapabilityPermission userPolicy) {
            return userPolicy(Output.of(userPolicy));
        }

        public Builder users(@Nullable Output<CapabilityPermission> users) {
            $.users = users;
            return this;
        }

        public Builder users(CapabilityPermission users) {
            return users(Output.of(users));
        }

        public Builder zone(@Nullable Output<CapabilityPermission> zone) {
            $.zone = zone;
            return this;
        }

        public Builder zone(CapabilityPermission zone) {
            return zone(Output.of(zone));
        }

        public CapabilitiesArgs build() {
            return $;
        }
    }

}
