// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.osmitgmbh.cephradosgw.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class QuotaArgsArgs extends com.pulumi.resources.ResourceArgs {

    public static final QuotaArgsArgs Empty = new QuotaArgsArgs();

    /**
     * Enable or disable quota enforcement quota
     * 
     */
    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    /**
     * @return Enable or disable quota enforcement quota
     * 
     */
    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * Maximum object count - numeric value (alternate to MaxObjectsHum)
     * 
     */
    @Import(name="maxObjects")
    private @Nullable Output<Integer> maxObjects;

    /**
     * @return Maximum object count - numeric value (alternate to MaxObjectsHum)
     * 
     */
    public Optional<Output<Integer>> maxObjects() {
        return Optional.ofNullable(this.maxObjects);
    }

    /**
     * Maximum object count - human readable format (i.e. 10k) (alternate to MaxObjects)
     * 
     */
    @Import(name="maxObjectsHum")
    private @Nullable Output<String> maxObjectsHum;

    /**
     * @return Maximum object count - human readable format (i.e. 10k) (alternate to MaxObjects)
     * 
     */
    public Optional<Output<String>> maxObjectsHum() {
        return Optional.ofNullable(this.maxObjectsHum);
    }

    /**
     * Maximum size - numeric value (alternate to MaxSizeHum)
     * 
     */
    @Import(name="maxSize")
    private @Nullable Output<Integer> maxSize;

    /**
     * @return Maximum size - numeric value (alternate to MaxSizeHum)
     * 
     */
    public Optional<Output<Integer>> maxSize() {
        return Optional.ofNullable(this.maxSize);
    }

    /**
     * Maximum size - human readable format (alternate to MaxSize)
     * 
     */
    @Import(name="maxSizeHum")
    private @Nullable Output<String> maxSizeHum;

    /**
     * @return Maximum size - human readable format (alternate to MaxSize)
     * 
     */
    public Optional<Output<String>> maxSizeHum() {
        return Optional.ofNullable(this.maxSizeHum);
    }

    private QuotaArgsArgs() {}

    private QuotaArgsArgs(QuotaArgsArgs $) {
        this.enabled = $.enabled;
        this.maxObjects = $.maxObjects;
        this.maxObjectsHum = $.maxObjectsHum;
        this.maxSize = $.maxSize;
        this.maxSizeHum = $.maxSizeHum;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(QuotaArgsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private QuotaArgsArgs $;

        public Builder() {
            $ = new QuotaArgsArgs();
        }

        public Builder(QuotaArgsArgs defaults) {
            $ = new QuotaArgsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param enabled Enable or disable quota enforcement quota
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled Enable or disable quota enforcement quota
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param maxObjects Maximum object count - numeric value (alternate to MaxObjectsHum)
         * 
         * @return builder
         * 
         */
        public Builder maxObjects(@Nullable Output<Integer> maxObjects) {
            $.maxObjects = maxObjects;
            return this;
        }

        /**
         * @param maxObjects Maximum object count - numeric value (alternate to MaxObjectsHum)
         * 
         * @return builder
         * 
         */
        public Builder maxObjects(Integer maxObjects) {
            return maxObjects(Output.of(maxObjects));
        }

        /**
         * @param maxObjectsHum Maximum object count - human readable format (i.e. 10k) (alternate to MaxObjects)
         * 
         * @return builder
         * 
         */
        public Builder maxObjectsHum(@Nullable Output<String> maxObjectsHum) {
            $.maxObjectsHum = maxObjectsHum;
            return this;
        }

        /**
         * @param maxObjectsHum Maximum object count - human readable format (i.e. 10k) (alternate to MaxObjects)
         * 
         * @return builder
         * 
         */
        public Builder maxObjectsHum(String maxObjectsHum) {
            return maxObjectsHum(Output.of(maxObjectsHum));
        }

        /**
         * @param maxSize Maximum size - numeric value (alternate to MaxSizeHum)
         * 
         * @return builder
         * 
         */
        public Builder maxSize(@Nullable Output<Integer> maxSize) {
            $.maxSize = maxSize;
            return this;
        }

        /**
         * @param maxSize Maximum size - numeric value (alternate to MaxSizeHum)
         * 
         * @return builder
         * 
         */
        public Builder maxSize(Integer maxSize) {
            return maxSize(Output.of(maxSize));
        }

        /**
         * @param maxSizeHum Maximum size - human readable format (alternate to MaxSize)
         * 
         * @return builder
         * 
         */
        public Builder maxSizeHum(@Nullable Output<String> maxSizeHum) {
            $.maxSizeHum = maxSizeHum;
            return this;
        }

        /**
         * @param maxSizeHum Maximum size - human readable format (alternate to MaxSize)
         * 
         * @return builder
         * 
         */
        public Builder maxSizeHum(String maxSizeHum) {
            return maxSizeHum(Output.of(maxSizeHum));
        }

        public QuotaArgsArgs build() {
            return $;
        }
    }

}
