// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

export interface CapabilitiesArgs {
    amzCache?: pulumi.Input<enums.CapabilityPermission | undefined>;
    bilog?: pulumi.Input<enums.CapabilityPermission | undefined>;
    buckets?: pulumi.Input<enums.CapabilityPermission | undefined>;
    datalog?: pulumi.Input<enums.CapabilityPermission | undefined>;
    info?: pulumi.Input<enums.CapabilityPermission | undefined>;
    mdlog?: pulumi.Input<enums.CapabilityPermission | undefined>;
    metadata?: pulumi.Input<enums.CapabilityPermission | undefined>;
    oidcProvider?: pulumi.Input<enums.CapabilityPermission | undefined>;
    ratelimit?: pulumi.Input<enums.CapabilityPermission | undefined>;
    roles?: pulumi.Input<enums.CapabilityPermission | undefined>;
    usage?: pulumi.Input<enums.CapabilityPermission | undefined>;
    userPolicy?: pulumi.Input<enums.CapabilityPermission | undefined>;
    users?: pulumi.Input<enums.CapabilityPermission | undefined>;
    zone?: pulumi.Input<enums.CapabilityPermission | undefined>;
}

export interface QuotaArgsArgs {
    /**
     * Enable or disable quota enforcement quota
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Maximum object count - numeric value (alternate to MaxObjectsHum)
     */
    maxObjects?: pulumi.Input<number | undefined>;
    /**
     * Maximum object count - human readable format (i.e. 10k) (alternate to MaxObjects)
     */
    maxObjectsHum?: pulumi.Input<string | undefined>;
    /**
     * Maximum size - numeric value (alternate to MaxSizeHum)
     */
    maxSize?: pulumi.Input<number | undefined>;
    /**
     * Maximum size - human readable format (alternate to MaxSize)
     */
    maxSizeHum?: pulumi.Input<string | undefined>;
}
