// Copyright 2023, OSMIT GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package provider

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/ceph/go-ceph/rgw/admin"
	"github.com/pulumi/pulumi-go-provider/infer"

	p "github.com/pulumi/pulumi-go-provider"
)

// Each resource has a controlling struct.
// Resource behavior is determined by implementing methods on the controlling struct.
// The `Create` method is mandatory, but other methods are optional.
// - Check: Remap inputs before they are typed.
// - Diff: Change how instances of a resource are compared.
// - Update: Mutate a resource in place.
// - Read: Get the state of a resource from the backing provider.
// - Delete: Custom logic when the resource is deleted.
// - Annotate: Describe fields and set defaults for a resource.
// - WireDependencies: Control how outputs and secrets flows through values.
type Key struct{}

// Each resource has in input struct, defining what arguments it accepts.
type KeyArgs struct {
	// User id (parent)
	UserID      string `pulumi:"userId"`
	// Sub user name
	SubUserName string `pulumi:"subUserName,optional"`

	AccessKey string `pulumi:"accessKey,optional"`
	SecretKey string `pulumi:"secretKey,optional"`
	KeyType   string `pulumi:"keyType,optional"`
}

func (m *KeyArgs) Annotate(a infer.Annotator) {
	a.Describe(&m.UserID, "User-ID of 'parent' user")
	a.Describe(&m.SubUserName, "Name of sub-user (optional)")
	a.Describe(&m.AccessKey, "The access key")
	a.Describe(&m.SecretKey, "The secret key")
	a.Describe(&m.KeyType, "key type - either 's3' or 'swift'")
}

// Each resource has a state, describing the fields that exist on the created resource.
type KeyState struct {
	// It is generally a good idea to embed args in outputs, but it isn't strictly necessary.
	KeyArgs
	// this config element was assimilated...
	// Required: true
	Assimilated bool `pulumi:"_assimilated"`
}

// All resources must implement Create at a minumum.
func (Key) Create(ctx context.Context, req infer.CreateRequest[KeyArgs]) (infer.CreateResponse[KeyState], error) {
	// bail out now when we are in preview mode
	if req.DryRun {
		return infer.CreateResponse[KeyState]{
			ID:     IdPreviewPrefix + req.Name,
			Output: KeyState{KeyArgs: req.Inputs},
		}, nil
	}

	retErr := func(err error) (infer.CreateResponse[KeyState], error) {
		return infer.CreateResponse[KeyState]{Output: KeyState{KeyArgs: req.Inputs}}, err
	}

	ce, _, err := initClient(ctx)
	if err != nil {
		return retErr(err)
	}

	// we have to get current keys to find new / autogenerated key
	user, err := ce.client.GetUser(ctx, admin.User{ID: req.Inputs.UserID})
	if err != nil {
		return retErr(err)
	}
	seen := make(map[string]bool, len(user.Keys))
	for _, key := range user.Keys {
		seen[key.AccessKey] = true
	}

	newKey := admin.UserKeySpec{
		User:    req.Inputs.UserID,
		UID:     req.Inputs.UserID,
		SubUser: req.Inputs.SubUserName,

		KeyType: ifte[string](req.Inputs.KeyType != "", req.Inputs.KeyType, "s3"),
	}

	if req.Inputs.AccessKey == "" || req.Inputs.SecretKey == "" {
		generateKey := true
		newKey.GenerateKey = &generateKey
	} else {
		newKey.AccessKey = req.Inputs.AccessKey
		newKey.SecretKey = req.Inputs.SecretKey
	}

	keys, err := ce.client.CreateKey(ctx, newKey)
	if err != nil {
		return retErr(err)
	}

	state := KeyState{KeyArgs: req.Inputs, Assimilated: false}
	for _, key := range *keys {
		if seen[key.AccessKey] {
			continue
		}

		parts := strings.SplitN(key.User, ":", 2)
		if len(parts) == 2 {
			state.UserID = parts[0]
			state.SubUserName = parts[1]
		} else {
			state.UserID = key.User
		}

		state.KeyType = key.KeyType
		state.AccessKey = key.AccessKey
		state.SecretKey = key.SecretKey
		break
	}

	id := fmt.Sprintf("%s:%s:%s", req.Inputs.KeyType, req.Inputs.UserID, req.Inputs.SubUserName)
	return infer.CreateResponse[KeyState]{ID: id, Output: state}, err
}

func (Key) Diff(ctx context.Context, req infer.DiffRequest[KeyArgs, KeyState]) (infer.DiffResponse, error) {
	diff := map[string]p.PropertyDiff{}
	if req.Inputs.UserID != req.State.UserID {
		diff["userId"] = p.PropertyDiff{Kind: p.UpdateReplace}
	}
	if req.Inputs.SubUserName != req.State.SubUserName {
		diff["subUserName"] = p.PropertyDiff{Kind: p.UpdateReplace}
	}
	if req.Inputs.KeyType != req.State.KeyType {
		diff["keyType"] = p.PropertyDiff{Kind: p.UpdateReplace}
	}
	if req.Inputs.AccessKey != req.State.AccessKey {
		diff["accessKey"] = p.PropertyDiff{Kind: p.UpdateReplace}
	}
	if req.Inputs.SecretKey != req.State.SecretKey {
		diff["secretKey"] = p.PropertyDiff{Kind: p.Update}
	}
	// if news.Email != olds.Email {
	// 	diff["email"] = p.PropertyDiff{Kind: p.Update}
	// }
	//diffWalk(ctx, diff, "tags", reflect.ValueOf(olds.Tags), reflect.ValueOf(news.Tags))

	if len(diff) > 0 {
		p.GetLogger(ctx).Infof("DIFF on Key %s: Found %d diffs: %v", req.ID, len(diff), diff)
	}
	return infer.DiffResponse{
		DeleteBeforeReplace: hasReplaceDiff(diff),
		HasChanges:          len(diff) > 0,
		DetailedDiff:        diff,
	}, nil
}

func (Key) Read(ctx context.Context, req infer.ReadRequest[KeyArgs, KeyState]) (infer.ReadResponse[KeyArgs, KeyState], error) {
	p.GetLogger(ctx).Infof("READ on %s[%s]: Keeping as this object was assimilated!", "Key", req.ID)
	parts := strings.SplitN(req.ID, ":", 2)
	if len(parts) != 2 {
		return infer.ReadResponse[KeyArgs, KeyState]{ID: req.ID, Inputs: req.Inputs, State: req.State}, errors.New(fmt.Sprintf("Error splitting up id `%s` into parts", req.ID))
	}

	ce, _, err := initClient(ctx)
	if err != nil {
		return infer.ReadResponse[KeyArgs, KeyState]{ID: req.ID, Inputs: req.Inputs, State: req.State}, err
	}
	user, err := ce.client.GetUser(ctx, admin.User{ID: parts[0]})
	if err != nil {
		return infer.ReadResponse[KeyArgs, KeyState]{ID: req.ID, Inputs: req.Inputs, State: req.State}, err
	}
	expectedUser := req.State.UserID
	if req.State.SubUserName != "" {
		expectedUser = req.State.UserID + ":" + req.State.SubUserName
	}

	var found bool
	var matchingKey admin.UserKeySpec
	for _, key := range user.Keys {
		if key.User == expectedUser && key.AccessKey == req.State.AccessKey && key.SecretKey == req.State.SecretKey {
			found = true
			matchingKey = key
			break
		}
	}

	if !found {
		return infer.ReadResponse[KeyArgs, KeyState]{ID: req.ID, Inputs: req.Inputs, State: req.State}, errors.New(fmt.Sprintf("Could not find Key `%s` within user `%s`", parts[1], parts[0]))
	}
	ret := KeyState{KeyArgs: req.Inputs, Assimilated: req.State.Assimilated}
	ret.AccessKey = matchingKey.AccessKey
	return infer.ReadResponse[KeyArgs, KeyState]{ID: req.ID, Inputs: req.Inputs, State: ret}, err
}

// func (*Key) Update(ctx p.Context, id string, olds KeyState, news KeyArgs, preview bool) (KeyState, error) {
// 	user, Key, err := KeyArgsToAPI(news)
// 	if err != nil {
// 		return olds, err
// 	}
// 	// bail out now when we are in preview mode
// 	if preview {
// 		return ToKeyState(news, olds), nil
// 	}
// 	ce, _, err := initClient(ctx)
// 	if err != nil {
// 		return olds, err
// 	}

// 	err = ce.client.ModifyKey(ctx, user, Key)
// 	if err != nil {
// 		return olds, err
// 	}

// 	readState, err := APItoKeyArgs(Key, olds.KeyArgs)
// 	return ToKeyState(readState, olds), err
// }

func (Key) Delete(ctx context.Context, req infer.DeleteRequest[KeyState]) (infer.DeleteResponse, error) {
	p.GetLogger(ctx).Infof("DELETE on %s[%s]: Keeping as this object was assimilated!", "Key", req.ID)
	ce, c, err := initClient(ctx)
	if err != nil {
		return infer.DeleteResponse{}, err
	}
	if req.State.Assimilated && !c.deleteAssimilated {
		p.GetLogger(ctx).Infof("DELETE on %s[%s]: Keeping as this object was assimilated!", "Key", req.ID)
		return infer.DeleteResponse{}, nil
	}

	return infer.DeleteResponse{}, ce.client.RemoveKey(ctx, admin.UserKeySpec{
		UID:       req.State.UserID,
		SubUser:   req.State.SubUserName,
		AccessKey: req.State.AccessKey,
		KeyType:   req.State.KeyType,
	})
}
