# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum

__all__ = [
    'CapabilityPermission',
    'KeyType',
    'SubUserPermission',
]


class CapabilityPermission(str, Enum):
    READ = "read"
    WRITE = "write"
    ASTERISK = "*"


class KeyType(str, Enum):
    S3 = "s3"
    SWIFT = "swift"


class SubUserPermission(str, Enum):
    NONE = "none"
    READ = "read"
    WRITE = "write"
    READ_WRITE = "readWrite"
    FULL_CONTROL = "fullControl"
