// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CephRadosgw.Inputs
{

    public sealed class CapabilitiesArgs : global::Pulumi.ResourceArgs
    {
        [Input("amzCache")]
        public Input<Pulumi.CephRadosgw.CapabilityPermission>? AmzCache { get; set; }

        [Input("bilog")]
        public Input<Pulumi.CephRadosgw.CapabilityPermission>? Bilog { get; set; }

        [Input("buckets")]
        public Input<Pulumi.CephRadosgw.CapabilityPermission>? Buckets { get; set; }

        [Input("datalog")]
        public Input<Pulumi.CephRadosgw.CapabilityPermission>? Datalog { get; set; }

        [Input("info")]
        public Input<Pulumi.CephRadosgw.CapabilityPermission>? Info { get; set; }

        [Input("mdlog")]
        public Input<Pulumi.CephRadosgw.CapabilityPermission>? Mdlog { get; set; }

        [Input("metadata")]
        public Input<Pulumi.CephRadosgw.CapabilityPermission>? Metadata { get; set; }

        [Input("oidcProvider")]
        public Input<Pulumi.CephRadosgw.CapabilityPermission>? OidcProvider { get; set; }

        [Input("ratelimit")]
        public Input<Pulumi.CephRadosgw.CapabilityPermission>? Ratelimit { get; set; }

        [Input("roles")]
        public Input<Pulumi.CephRadosgw.CapabilityPermission>? Roles { get; set; }

        [Input("usage")]
        public Input<Pulumi.CephRadosgw.CapabilityPermission>? Usage { get; set; }

        [Input("userPolicy")]
        public Input<Pulumi.CephRadosgw.CapabilityPermission>? UserPolicy { get; set; }

        [Input("users")]
        public Input<Pulumi.CephRadosgw.CapabilityPermission>? Users { get; set; }

        [Input("zone")]
        public Input<Pulumi.CephRadosgw.CapabilityPermission>? Zone { get; set; }

        public CapabilitiesArgs()
        {
        }
        public static new CapabilitiesArgs Empty => new CapabilitiesArgs();
    }
}
