// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CephRadosgw.Inputs
{

    public sealed class QuotaArgsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enable or disable quota enforcement quota
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Maximum object count - numeric value (alternate to MaxObjectsHum)
        /// </summary>
        [Input("maxObjects")]
        public Input<int>? MaxObjects { get; set; }

        /// <summary>
        /// Maximum object count - human readable format (i.e. 10k) (alternate to MaxObjects)
        /// </summary>
        [Input("maxObjectsHum")]
        public Input<string>? MaxObjectsHum { get; set; }

        /// <summary>
        /// Maximum size - numeric value (alternate to MaxSizeHum)
        /// </summary>
        [Input("maxSize")]
        public Input<int>? MaxSize { get; set; }

        /// <summary>
        /// Maximum size - human readable format (alternate to MaxSize)
        /// </summary>
        [Input("maxSizeHum")]
        public Input<string>? MaxSizeHum { get; set; }

        public QuotaArgsArgs()
        {
        }
        public static new QuotaArgsArgs Empty => new QuotaArgsArgs();
    }
}
