# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

accessKeyID: Optional[str]
"""
The username. It's important but not secret.
"""

assimilate: Optional[str]
"""
Assimilate an existing object during create
"""

deleteAssimilated: Optional[str]
"""
Delete assimilated objects during delete (otherwise they would be kept on OpenZiti)
"""

endpoint: Optional[str]
"""
The URI to the API
"""

secretAccessKey: Optional[str]
"""
The password. It is very secret.
"""

version: Optional[str]

