// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

export class Bucket extends pulumi.CustomResource {
    /**
     * Get an existing Bucket resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Bucket {
        return new Bucket(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'ceph-radosgw:index:Bucket';

    /**
     * Returns true if the given object is an instance of Bucket.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Bucket {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Bucket.__pulumiType;
    }

    /**
     * Bucket was 'assimilated' - managing an existing bucket.
     */
    public /*out*/ readonly _assimilated!: pulumi.Output<boolean>;
    public /*out*/ readonly _location!: pulumi.Output<string>;
    /**
     * Bucket name
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Bucket object locking enabled
     */
    public readonly objectLocking!: pulumi.Output<boolean | undefined>;
    /**
     * Purge bucket on delete.
     */
    public readonly purgeOnDelete!: pulumi.Output<boolean | undefined>;
    /**
     * Bucket quota configuration
     */
    public readonly quota!: pulumi.Output<outputs.QuotaArgs | undefined>;
    /**
     * The unique bucket id.
     */
    public /*out*/ readonly ubid!: pulumi.Output<string>;
    public readonly versioning!: pulumi.Output<boolean | undefined>;

    /**
     * Create a Bucket resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BucketArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["objectLocking"] = args ? args.objectLocking : undefined;
            resourceInputs["purgeOnDelete"] = args ? args.purgeOnDelete : undefined;
            resourceInputs["quota"] = args ? args.quota : undefined;
            resourceInputs["versioning"] = args ? args.versioning : undefined;
            resourceInputs["_assimilated"] = undefined /*out*/;
            resourceInputs["_location"] = undefined /*out*/;
            resourceInputs["ubid"] = undefined /*out*/;
        } else {
            resourceInputs["_assimilated"] = undefined /*out*/;
            resourceInputs["_location"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["objectLocking"] = undefined /*out*/;
            resourceInputs["purgeOnDelete"] = undefined /*out*/;
            resourceInputs["quota"] = undefined /*out*/;
            resourceInputs["ubid"] = undefined /*out*/;
            resourceInputs["versioning"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Bucket.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Bucket resource.
 */
export interface BucketArgs {
    /**
     * Bucket name
     */
    name: pulumi.Input<string>;
    /**
     * Bucket object locking enabled
     */
    objectLocking?: pulumi.Input<boolean>;
    /**
     * Purge bucket on delete
     */
    purgeOnDelete?: pulumi.Input<boolean>;
    /**
     * Bucket quota configuration
     */
    quota?: pulumi.Input<inputs.QuotaArgsArgs>;
    versioning?: pulumi.Input<boolean>;
}
