// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

export class SubUser extends pulumi.CustomResource {
    /**
     * Get an existing SubUser resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): SubUser {
        return new SubUser(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'ceph-radosgw:index:SubUser';

    /**
     * Returns true if the given object is an instance of SubUser.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SubUser {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SubUser.__pulumiType;
    }

    declare public /*out*/ readonly _assimilated: pulumi.Output<boolean>;
    declare public /*out*/ readonly fullname: pulumi.Output<string>;
    declare public readonly generateKey: pulumi.Output<boolean | undefined>;
    declare public readonly keyType: pulumi.Output<enums.KeyType | undefined>;
    declare public /*out*/ readonly keys: pulumi.Output<outputs.KeyEntry[]>;
    declare public readonly permissions: pulumi.Output<enums.SubUserPermission>;
    declare public readonly purgeKeys: pulumi.Output<boolean | undefined>;
    declare public readonly secretKey: pulumi.Output<string | undefined>;
    /**
     * Name of this subuser
     */
    declare public readonly subUserName: pulumi.Output<string>;
    /**
     * User-ID of 'parent' user
     */
    declare public readonly userId: pulumi.Output<string>;

    /**
     * Create a SubUser resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SubUserArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.permissions === undefined && !opts.urn) {
                throw new Error("Missing required property 'permissions'");
            }
            if (args?.subUserName === undefined && !opts.urn) {
                throw new Error("Missing required property 'subUserName'");
            }
            if (args?.userId === undefined && !opts.urn) {
                throw new Error("Missing required property 'userId'");
            }
            resourceInputs["generateKey"] = args?.generateKey;
            resourceInputs["keyType"] = args?.keyType;
            resourceInputs["permissions"] = args?.permissions;
            resourceInputs["purgeKeys"] = args?.purgeKeys;
            resourceInputs["secretKey"] = args?.secretKey ? pulumi.secret(args.secretKey) : undefined;
            resourceInputs["subUserName"] = args?.subUserName;
            resourceInputs["userId"] = args?.userId;
            resourceInputs["_assimilated"] = undefined /*out*/;
            resourceInputs["fullname"] = undefined /*out*/;
            resourceInputs["keys"] = undefined /*out*/;
        } else {
            resourceInputs["_assimilated"] = undefined /*out*/;
            resourceInputs["fullname"] = undefined /*out*/;
            resourceInputs["generateKey"] = undefined /*out*/;
            resourceInputs["keyType"] = undefined /*out*/;
            resourceInputs["keys"] = undefined /*out*/;
            resourceInputs["permissions"] = undefined /*out*/;
            resourceInputs["purgeKeys"] = undefined /*out*/;
            resourceInputs["secretKey"] = undefined /*out*/;
            resourceInputs["subUserName"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["secretKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(SubUser.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a SubUser resource.
 */
export interface SubUserArgs {
    generateKey?: pulumi.Input<boolean | undefined>;
    keyType?: pulumi.Input<enums.KeyType | undefined>;
    permissions: pulumi.Input<enums.SubUserPermission>;
    purgeKeys?: pulumi.Input<boolean | undefined>;
    secretKey?: pulumi.Input<string | undefined>;
    /**
     * Name of this subuser
     */
    subUserName: pulumi.Input<string>;
    /**
     * User-ID of 'parent' user
     */
    userId: pulumi.Input<string>;
}
